{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "global-events",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "global-events-1.0.0.jar",
          "url": "global-events-1.0.0.jar",
          "size": 7286,
          "sha512": "ef2f09433bccf1d501a6bb3ca8abee133a566623d5251d5189b19012c936bff3ee82bc9fd3c507abbd6d1d773c1fc0e3cea19ed07b3505df92190163bfc1212b",
          "sha256": "74fefbfc132f1f42ce3dbe64d296d9bacc6b1b764ccdbe44a63cdb2d96cfc418",
          "sha1": "b172aad87d983d1eaf2f6c5990a32a47637768c2",
          "md5": "25746c9c23dd8cc0d6d3b3ee028db3de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "global-events-1.0.0.jar",
          "url": "global-events-1.0.0.jar",
          "size": 7286,
          "sha512": "ef2f09433bccf1d501a6bb3ca8abee133a566623d5251d5189b19012c936bff3ee82bc9fd3c507abbd6d1d773c1fc0e3cea19ed07b3505df92190163bfc1212b",
          "sha256": "74fefbfc132f1f42ce3dbe64d296d9bacc6b1b764ccdbe44a63cdb2d96cfc418",
          "sha1": "b172aad87d983d1eaf2f6c5990a32a47637768c2",
          "md5": "25746c9c23dd8cc0d6d3b3ee028db3de"
        }
      ]
    }
  ]
}
