{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "global-events",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "global-events-1.0.0.jar",
          "url": "global-events-1.0.0.jar",
          "size": 7180,
          "sha512": "a4b0afa94056e0b514ae542736059ede3c86c805399c6138dc7d2a49eea9fab8b3a56a6b93b80ad46b1fd5f22048a360781a1d5f09197a242c359dfaab37f4cd",
          "sha256": "2dd4bde6e05881e4c3bb7a7a430d008633a5f3fdc45d4a81d1dd83f310c586be",
          "sha1": "ecaa967b55464b2ccdacc18d4527b8c930a6c488",
          "md5": "cb89241d32330a831400e8f7c655e451"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "global-events-1.0.0.jar",
          "url": "global-events-1.0.0.jar",
          "size": 7180,
          "sha512": "a4b0afa94056e0b514ae542736059ede3c86c805399c6138dc7d2a49eea9fab8b3a56a6b93b80ad46b1fd5f22048a360781a1d5f09197a242c359dfaab37f4cd",
          "sha256": "2dd4bde6e05881e4c3bb7a7a430d008633a5f3fdc45d4a81d1dd83f310c586be",
          "sha1": "ecaa967b55464b2ccdacc18d4527b8c930a6c488",
          "md5": "cb89241d32330a831400e8f7c655e451"
        }
      ]
    }
  ]
}
