{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "mzmine-test-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mzmine-test-utils-1.0.0.jar",
          "url": "mzmine-test-utils-1.0.0.jar",
          "size": 2669,
          "sha512": "3bd57d7bcd385fa2a77cb1fa3ca8b78a55234d1ee723d5654f8bd2b8e2d04c387363e059cd40ff1866f6e1efb6ba619b444383ae6c759a0cfd26962409ee30d3",
          "sha256": "763b774d510b5907e2c79f9c19bff9437cf8ba0e45d3b8976ed581e7c1fee0ce",
          "sha1": "dad2c61626235a48d11836fe2fd92d605ceae7d6",
          "md5": "aee9ebfe980268a39e18a7d1c94a9ff2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "taskcontroller",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "mzmine-test-utils-1.0.0.jar",
          "url": "mzmine-test-utils-1.0.0.jar",
          "size": 2669,
          "sha512": "3bd57d7bcd385fa2a77cb1fa3ca8b78a55234d1ee723d5654f8bd2b8e2d04c387363e059cd40ff1866f6e1efb6ba619b444383ae6c759a0cfd26962409ee30d3",
          "sha256": "763b774d510b5907e2c79f9c19bff9437cf8ba0e45d3b8976ed581e7c1fee0ce",
          "sha1": "dad2c61626235a48d11836fe2fd92d605ceae7d6",
          "md5": "aee9ebfe980268a39e18a7d1c94a9ff2"
        }
      ]
    }
  ]
}
