{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "mzmine-test-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mzmine-test-utils-1.0.0.jar",
          "url": "mzmine-test-utils-1.0.0.jar",
          "size": 1137,
          "sha512": "0ab5aa336fc683bc928c6d339405b9c284020447b2d5c080816243c5d1f559382d4ae05cf317f8f1532baa57aeddd6c75f6be06e40c85276f21d6b57f1d3e223",
          "sha256": "311747af0e14b198cad07863405c9eb055356316d5fcf81ecd1f402ce5ed7294",
          "sha1": "f81fa4f6b78b19d465314e877e195cdd8c7c2a7c",
          "md5": "bb3541abcb1205fd21a951ff6af591da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "taskcontroller",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "mzmine-test-utils-1.0.0.jar",
          "url": "mzmine-test-utils-1.0.0.jar",
          "size": 1137,
          "sha512": "0ab5aa336fc683bc928c6d339405b9c284020447b2d5c080816243c5d1f559382d4ae05cf317f8f1532baa57aeddd6c75f6be06e40c85276f21d6b57f1d3e223",
          "sha256": "311747af0e14b198cad07863405c9eb055356316d5fcf81ecd1f402ce5ed7294",
          "sha1": "f81fa4f6b78b19d465314e877e195cdd8c7c2a7c",
          "md5": "bb3541abcb1205fd21a951ff6af591da"
        }
      ]
    }
  ]
}
