package io.github.mzmine.modules.dataprocessing.id_lipididentification.common.lipididentificationtools.matchedlipidannotations.specieslevellipidmatches;

public class FattyAcylSpeciesLevelMatchedLipidFactory extends
    GlyceroAndGlycerophosphoSpeciesLevelMatchedLipidFactory implements
    ISpeciesLevelMatchedLipidFactory {

}
