{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 70299,
          "sha512": "0327ba2d1162cca9017c68a78f768f0e5a00c654b9b36054be84920f24599b9202dc8a98765f1e2da3aaf65ea0817f0e4b357de4eba6f580aa2767b71fcf09e3",
          "sha256": "dcdc7f3d02c28c372164818f755d3164009d03923c1ae1ba0b08b313d56edfb5",
          "sha1": "d36cee348399f5bc0533720d93a4191f0cbcb9bf",
          "md5": "6454abb036e1ce1477c6c5919e502bb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.keycloak",
          "module": "keycloak-installed-adapter",
          "version": {
            "requires": "24.0.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient-win",
          "version": {
            "requires": "4.5.14"
          }
        }
      ],
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 70299,
          "sha512": "0327ba2d1162cca9017c68a78f768f0e5a00c654b9b36054be84920f24599b9202dc8a98765f1e2da3aaf65ea0817f0e4b357de4eba6f580aa2767b71fcf09e3",
          "sha256": "dcdc7f3d02c28c372164818f755d3164009d03923c1ae1ba0b08b313d56edfb5",
          "sha1": "d36cee348399f5bc0533720d93a4191f0cbcb9bf",
          "md5": "6454abb036e1ce1477c6c5919e502bb4"
        }
      ]
    }
  ]
}
