{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 66235,
          "sha512": "66575b1b0ca0cae935545d6a6ff1693b89a8ad672500309d4a5a0c7ec71202bd0454ab273e801076f2b0a72b2f773bc44149e72544a131938d74f527e001af16",
          "sha256": "fb0d2b8aca5b18547e17ad40ed53b6698dce729ab7cdaed13cce37edfa4b2abf",
          "sha1": "f90598a6498ea88f8ba15075b1b6ab9bb2e3e35b",
          "md5": "9580a8cb304382065b36d91946f71bb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.keycloak",
          "module": "keycloak-installed-adapter",
          "version": {
            "requires": "24.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 66235,
          "sha512": "66575b1b0ca0cae935545d6a6ff1693b89a8ad672500309d4a5a0c7ec71202bd0454ab273e801076f2b0a72b2f773bc44149e72544a131938d74f527e001af16",
          "sha256": "fb0d2b8aca5b18547e17ad40ed53b6698dce729ab7cdaed13cce37edfa4b2abf",
          "sha1": "f90598a6498ea88f8ba15075b1b6ab9bb2e3e35b",
          "md5": "9580a8cb304382065b36d91946f71bb0"
        }
      ]
    }
  ]
}
