{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 67787,
          "sha512": "1ec99d65849fd82f18f05161390bb27e69cca2e7070cb3dd94b4e690c8ab6a4890aeb9e7fe2fffe31791664dde96f99108664bee4031488230cbe9da39e3e567",
          "sha256": "091be6ae66d15b2833106de8cd86398693e23fece1dd0c112da0787f933d4863",
          "sha1": "6f5c8f08c2e63a3c751c52a32408810b92e21dd8",
          "md5": "0efcfde0aa0a2247e9dc59b72b216d04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.keycloak",
          "module": "keycloak-installed-adapter",
          "version": {
            "requires": "24.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 67787,
          "sha512": "1ec99d65849fd82f18f05161390bb27e69cca2e7070cb3dd94b4e690c8ab6a4890aeb9e7fe2fffe31791664dde96f99108664bee4031488230cbe9da39e3e567",
          "sha256": "091be6ae66d15b2833106de8cd86398693e23fece1dd0c112da0787f933d4863",
          "sha1": "6f5c8f08c2e63a3c751c52a32408810b92e21dd8",
          "md5": "0efcfde0aa0a2247e9dc59b72b216d04"
        }
      ]
    }
  ]
}
