/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_wiff2;

import static java.lang.foreign.ValueLayout.OfBoolean;
import static java.lang.foreign.ValueLayout.OfByte;
import static java.lang.foreign.ValueLayout.OfDouble;
import static java.lang.foreign.ValueLayout.OfFloat;
import static java.lang.foreign.ValueLayout.OfInt;
import static java.lang.foreign.ValueLayout.OfLong;
import static java.lang.foreign.ValueLayout.OfShort;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.PaddingLayout;
import java.lang.foreign.SequenceLayout;
import java.lang.foreign.StructLayout;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.util.Arrays;
import java.util.stream.Collectors;

public class Wiff2LauncherLib_h$shared {

  Wiff2LauncherLib_h$shared() {
    // Should not be called directly
  }

  public static final OfBoolean C_BOOL = (OfBoolean) Linker.nativeLinker().canonicalLayouts()
      .get("bool");
  public static final OfByte C_CHAR = (OfByte) Linker.nativeLinker().canonicalLayouts().get("char");
  public static final OfShort C_SHORT = (OfShort) Linker.nativeLinker().canonicalLayouts()
      .get("short");
  public static final OfInt C_INT = (OfInt) Linker.nativeLinker().canonicalLayouts().get("int");
  public static final OfLong C_LONG_LONG = (OfLong) Linker.nativeLinker().canonicalLayouts()
      .get("long long");
  public static final OfFloat C_FLOAT = (OfFloat) Linker.nativeLinker().canonicalLayouts()
      .get("float");
  public static final OfDouble C_DOUBLE = (OfDouble) Linker.nativeLinker().canonicalLayouts()
      .get("double");
  public static final AddressLayout C_POINTER = ((AddressLayout) Linker.nativeLinker()
      .canonicalLayouts().get("void*")).withTargetLayout(
      MemoryLayout.sequenceLayout(Long.MAX_VALUE, C_CHAR));
  public static final ValueLayout C_LONG = (ValueLayout) Linker.nativeLinker().canonicalLayouts().get("long");
  public static final OfDouble C_LONG_DOUBLE = (OfDouble) Linker.nativeLinker().canonicalLayouts()
      .get("double");

  static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

  static void traceDowncall(String name, Object... args) {
    String traceArgs = Arrays.stream(args).map(Object::toString).collect(Collectors.joining(", "));
    System.out.printf("%s(%s)\n", name, traceArgs);
  }

  static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
    try {
      return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
    } catch (ReflectiveOperationException ex) {
      throw new AssertionError(ex);
    }
  }

  static MemoryLayout align(MemoryLayout layout, long align) {
    return switch (layout) {
      case PaddingLayout p -> p;
      case ValueLayout v -> v.withByteAlignment(align);
      case GroupLayout g -> {
        MemoryLayout[] alignedMembers = g.memberLayouts().stream().map(m -> align(m, align))
            .toArray(MemoryLayout[]::new);
        yield g instanceof StructLayout ? MemoryLayout.structLayout(alignedMembers)
            : MemoryLayout.unionLayout(alignedMembers);
      }
      case SequenceLayout s ->
          MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
    };
  }
}

