{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 23429,
          "sha512": "7a9cef5e4e73fbd4669fa39c662455c3afa6a2df2ef9156f9a8e90be249f105f33a1e05c59d10a65de06027d30e521f2873f8458fdee57460da3b166e2a132e2",
          "sha256": "660ec781d7650f8a6561ef4a994eebb6c0678fe2e06d4e6471a8a92f2fce5a82",
          "sha1": "826cc36ecdc30c2bed5c63d7f1f13769fef6724c",
          "md5": "2a8a50bf919afcb4282bb5f4bfdca152"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 23429,
          "sha512": "7a9cef5e4e73fbd4669fa39c662455c3afa6a2df2ef9156f9a8e90be249f105f33a1e05c59d10a65de06027d30e521f2873f8458fdee57460da3b166e2a132e2",
          "sha256": "660ec781d7650f8a6561ef4a994eebb6c0678fe2e06d4e6471a8a92f2fce5a82",
          "sha1": "826cc36ecdc30c2bed5c63d7f1f13769fef6724c",
          "md5": "2a8a50bf919afcb4282bb5f4bfdca152"
        }
      ]
    }
  ]
}
