{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 8491,
          "sha512": "a52d22c9d80df1515091c1bf517359707ba50e91cab2e3890728d070b3a069018178d1a473424bcc87911bdfb0b2b92a50a1de74bf3f160b36ae84bbbd83fa55",
          "sha256": "cc54cc8717b0956b94b665dbf00e907e1a1d24e93a2b0290743056c966fb0171",
          "sha1": "4c0dc3c234f96a083b40cb8cb64306f05f01bb09",
          "md5": "e938a132987bcbb67610dd4c70d781cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 8491,
          "sha512": "a52d22c9d80df1515091c1bf517359707ba50e91cab2e3890728d070b3a069018178d1a473424bcc87911bdfb0b2b92a50a1de74bf3f160b36ae84bbbd83fa55",
          "sha256": "cc54cc8717b0956b94b665dbf00e907e1a1d24e93a2b0290743056c966fb0171",
          "sha1": "4c0dc3c234f96a083b40cb8cb64306f05f01bb09",
          "md5": "e938a132987bcbb67610dd4c70d781cb"
        }
      ]
    }
  ]
}
