// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_bruker_tdf.datamodel;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     isolation_setting optional_isolation;
 *     bool has_isolation;
 *     fragmentation_settings fragmentation;
 *     int64_t optional_precursor_id;
 *     bool has_precursor_id;
 *     int64_t optional_prm_target_id;
 *     bool has_prm_target_id;
 * }
 * }
 */
public class isolation_fragmentation_step {

    isolation_fragmentation_step() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        isolation_setting.layout().withName("optional_isolation"),
        TDFLib.C_BOOL.withName("has_isolation"),
        MemoryLayout.paddingLayout(7),
        fragmentation_settings.layout().withName("fragmentation"),
        TDFLib.C_LONG_LONG.withName("optional_precursor_id"),
        TDFLib.C_BOOL.withName("has_precursor_id"),
        MemoryLayout.paddingLayout(7),
        TDFLib.C_LONG_LONG.withName("optional_prm_target_id"),
        TDFLib.C_BOOL.withName("has_prm_target_id"),
        MemoryLayout.paddingLayout(7)
    ).withName("$anon$112:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout optional_isolation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("optional_isolation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * isolation_setting optional_isolation
     * }
     */
    public static final GroupLayout optional_isolation$layout() {
        return optional_isolation$LAYOUT;
    }

    private static final long optional_isolation$OFFSET = $LAYOUT.byteOffset(groupElement("optional_isolation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * isolation_setting optional_isolation
     * }
     */
    public static final long optional_isolation$offset() {
        return optional_isolation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * isolation_setting optional_isolation
     * }
     */
    public static MemorySegment optional_isolation(MemorySegment struct) {
        return struct.asSlice(optional_isolation$OFFSET, optional_isolation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * isolation_setting optional_isolation
     * }
     */
    public static void optional_isolation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, optional_isolation$OFFSET, optional_isolation$LAYOUT.byteSize());
    }

    private static final OfBoolean has_isolation$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("has_isolation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool has_isolation
     * }
     */
    public static final OfBoolean has_isolation$layout() {
        return has_isolation$LAYOUT;
    }

    private static final long has_isolation$OFFSET = $LAYOUT.byteOffset(groupElement("has_isolation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool has_isolation
     * }
     */
    public static final long has_isolation$offset() {
        return has_isolation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool has_isolation
     * }
     */
    public static boolean has_isolation(MemorySegment struct) {
        return struct.get(has_isolation$LAYOUT, has_isolation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool has_isolation
     * }
     */
    public static void has_isolation(MemorySegment struct, boolean fieldValue) {
        struct.set(has_isolation$LAYOUT, has_isolation$OFFSET, fieldValue);
    }

    private static final GroupLayout fragmentation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("fragmentation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * fragmentation_settings fragmentation
     * }
     */
    public static final GroupLayout fragmentation$layout() {
        return fragmentation$LAYOUT;
    }

    private static final long fragmentation$OFFSET = $LAYOUT.byteOffset(groupElement("fragmentation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * fragmentation_settings fragmentation
     * }
     */
    public static final long fragmentation$offset() {
        return fragmentation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * fragmentation_settings fragmentation
     * }
     */
    public static MemorySegment fragmentation(MemorySegment struct) {
        return struct.asSlice(fragmentation$OFFSET, fragmentation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * fragmentation_settings fragmentation
     * }
     */
    public static void fragmentation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fragmentation$OFFSET, fragmentation$LAYOUT.byteSize());
    }

    private static final OfLong optional_precursor_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("optional_precursor_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t optional_precursor_id
     * }
     */
    public static final OfLong optional_precursor_id$layout() {
        return optional_precursor_id$LAYOUT;
    }

    private static final long optional_precursor_id$OFFSET = $LAYOUT.byteOffset(groupElement("optional_precursor_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t optional_precursor_id
     * }
     */
    public static final long optional_precursor_id$offset() {
        return optional_precursor_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t optional_precursor_id
     * }
     */
    public static long optional_precursor_id(MemorySegment struct) {
        return struct.get(optional_precursor_id$LAYOUT, optional_precursor_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t optional_precursor_id
     * }
     */
    public static void optional_precursor_id(MemorySegment struct, long fieldValue) {
        struct.set(optional_precursor_id$LAYOUT, optional_precursor_id$OFFSET, fieldValue);
    }

    private static final OfBoolean has_precursor_id$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("has_precursor_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool has_precursor_id
     * }
     */
    public static final OfBoolean has_precursor_id$layout() {
        return has_precursor_id$LAYOUT;
    }

    private static final long has_precursor_id$OFFSET = $LAYOUT.byteOffset(groupElement("has_precursor_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool has_precursor_id
     * }
     */
    public static final long has_precursor_id$offset() {
        return has_precursor_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool has_precursor_id
     * }
     */
    public static boolean has_precursor_id(MemorySegment struct) {
        return struct.get(has_precursor_id$LAYOUT, has_precursor_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool has_precursor_id
     * }
     */
    public static void has_precursor_id(MemorySegment struct, boolean fieldValue) {
        struct.set(has_precursor_id$LAYOUT, has_precursor_id$OFFSET, fieldValue);
    }

    private static final OfLong optional_prm_target_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("optional_prm_target_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t optional_prm_target_id
     * }
     */
    public static final OfLong optional_prm_target_id$layout() {
        return optional_prm_target_id$LAYOUT;
    }

    private static final long optional_prm_target_id$OFFSET = $LAYOUT.byteOffset(groupElement("optional_prm_target_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t optional_prm_target_id
     * }
     */
    public static final long optional_prm_target_id$offset() {
        return optional_prm_target_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t optional_prm_target_id
     * }
     */
    public static long optional_prm_target_id(MemorySegment struct) {
        return struct.get(optional_prm_target_id$LAYOUT, optional_prm_target_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t optional_prm_target_id
     * }
     */
    public static void optional_prm_target_id(MemorySegment struct, long fieldValue) {
        struct.set(optional_prm_target_id$LAYOUT, optional_prm_target_id$OFFSET, fieldValue);
    }

    private static final OfBoolean has_prm_target_id$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("has_prm_target_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool has_prm_target_id
     * }
     */
    public static final OfBoolean has_prm_target_id$layout() {
        return has_prm_target_id$LAYOUT;
    }

    private static final long has_prm_target_id$OFFSET = $LAYOUT.byteOffset(groupElement("has_prm_target_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool has_prm_target_id
     * }
     */
    public static final long has_prm_target_id$offset() {
        return has_prm_target_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool has_prm_target_id
     * }
     */
    public static boolean has_prm_target_id(MemorySegment struct) {
        return struct.get(has_prm_target_id$LAYOUT, has_prm_target_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool has_prm_target_id
     * }
     */
    public static void has_prm_target_id(MemorySegment struct, boolean fieldValue) {
        struct.set(has_prm_target_id$LAYOUT, has_prm_target_id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

