// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_bruker_tdf.datamodel;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     double mz;
 *     double width;
 *     tims_isolation optional_tims_isolation;
 *     bool has_tims_isolation;
 * }
 * }
 */
public class isolation_setting {

    isolation_setting() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TDFLib.C_DOUBLE.withName("mz"),
        TDFLib.C_DOUBLE.withName("width"),
        tims_isolation.layout().withName("optional_tims_isolation"),
        TDFLib.C_BOOL.withName("has_tims_isolation"),
        MemoryLayout.paddingLayout(7)
    ).withName("$anon$103:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble mz$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("mz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double mz
     * }
     */
    public static final OfDouble mz$layout() {
        return mz$LAYOUT;
    }

    private static final long mz$OFFSET = $LAYOUT.byteOffset(groupElement("mz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double mz
     * }
     */
    public static final long mz$offset() {
        return mz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double mz
     * }
     */
    public static double mz(MemorySegment struct) {
        return struct.get(mz$LAYOUT, mz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double mz
     * }
     */
    public static void mz(MemorySegment struct, double fieldValue) {
        struct.set(mz$LAYOUT, mz$OFFSET, fieldValue);
    }

    private static final OfDouble width$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double width
     * }
     */
    public static final OfDouble width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double width
     * }
     */
    public static double width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double width
     * }
     */
    public static void width(MemorySegment struct, double fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final GroupLayout optional_tims_isolation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("optional_tims_isolation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * tims_isolation optional_tims_isolation
     * }
     */
    public static final GroupLayout optional_tims_isolation$layout() {
        return optional_tims_isolation$LAYOUT;
    }

    private static final long optional_tims_isolation$OFFSET = $LAYOUT.byteOffset(groupElement("optional_tims_isolation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * tims_isolation optional_tims_isolation
     * }
     */
    public static final long optional_tims_isolation$offset() {
        return optional_tims_isolation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * tims_isolation optional_tims_isolation
     * }
     */
    public static MemorySegment optional_tims_isolation(MemorySegment struct) {
        return struct.asSlice(optional_tims_isolation$OFFSET, optional_tims_isolation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * tims_isolation optional_tims_isolation
     * }
     */
    public static void optional_tims_isolation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, optional_tims_isolation$OFFSET, optional_tims_isolation$LAYOUT.byteSize());
    }

    private static final OfBoolean has_tims_isolation$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("has_tims_isolation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool has_tims_isolation
     * }
     */
    public static final OfBoolean has_tims_isolation$layout() {
        return has_tims_isolation$LAYOUT;
    }

    private static final long has_tims_isolation$OFFSET = $LAYOUT.byteOffset(groupElement("has_tims_isolation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool has_tims_isolation
     * }
     */
    public static final long has_tims_isolation$offset() {
        return has_tims_isolation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool has_tims_isolation
     * }
     */
    public static boolean has_tims_isolation(MemorySegment struct) {
        return struct.get(has_tims_isolation$LAYOUT, has_tims_isolation$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool has_tims_isolation
     * }
     */
    public static void has_tims_isolation(MemorySegment struct, boolean fieldValue) {
        struct.set(has_tims_isolation$LAYOUT, has_tims_isolation$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

