// Generated by jextract

package io.github.mzmine.modules.io.import_rawdata_bruker_tdf.datamodel;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (msms_profile_spectrum_function)(int64_t, uint32_t, const int32_t *, void *)
 * }
 */
public final class msms_profile_spectrum_function {

    private msms_profile_spectrum_function() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(long id, int num_points, MemorySegment intensity_values, MemorySegment user_data);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        TDFLib.C_LONG_LONG,
        TDFLib.C_INT,
        TDFLib.C_POINTER,
        TDFLib.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = TDFLib.upcallHandle(msms_profile_spectrum_function.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(msms_profile_spectrum_function.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, long id, int num_points, MemorySegment intensity_values, MemorySegment user_data) {
        try {
             DOWN$MH.invokeExact(funcPtr, id, num_points, intensity_values, user_data);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

