package io.github.mzmine.modules.dataprocessing.id_lipididentification.common.lipididentificationtools.matchedlipidannotations.molecularspecieslevelidentities;

public class SterolMolecularSpeciesLevelMatchedLipidFactory extends
    GlyceroAndPhosphoMolecularSpeciesLevelMatchedLipidFactory implements
    IMolecularSpeciesLevelMatchedLipidFactory {

}
