/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface AdcChannelsDescriptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.AdcChannelsDescriptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * provides the mapping to the user defined names of the ADC channels
   * </pre>
   *
   * <code>map&lt;int32, string&gt; Names = 1;</code>
   */
  int getNamesCount();
  /**
   * <pre>
   * provides the mapping to the user defined names of the ADC channels
   * </pre>
   *
   * <code>map&lt;int32, string&gt; Names = 1;</code>
   */
  boolean containsNames(
      int key);
  /**
   * Use {@link #getNamesMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, String>
  getNames();
  /**
   * <pre>
   * provides the mapping to the user defined names of the ADC channels
   * </pre>
   *
   * <code>map&lt;int32, string&gt; Names = 1;</code>
   */
  java.util.Map<Integer, String>
  getNamesMap();
  /**
   * <pre>
   * provides the mapping to the user defined names of the ADC channels
   * </pre>
   *
   * <code>map&lt;int32, string&gt; Names = 1;</code>
   */
  /* nullable */
String getNamesOrDefault(
      int key,
      /* nullable */
String defaultValue);
  /**
   * <pre>
   * provides the mapping to the user defined names of the ADC channels
   * </pre>
   *
   * <code>map&lt;int32, string&gt; Names = 1;</code>
   */
  String getNamesOrThrow(
      int key);

  /**
   * <pre>
   * additional user defined attributes that describe ADC channels
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 2;</code>
   */
  java.util.List<ControlledVocabularyParameter>
      getAttributesList();
  /**
   * <pre>
   * additional user defined attributes that describe ADC channels
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 2;</code>
   */
  ControlledVocabularyParameter getAttributes(int index);
  /**
   * <pre>
   * additional user defined attributes that describe ADC channels
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 2;</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * additional user defined attributes that describe ADC channels
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 2;</code>
   */
  java.util.List<? extends ControlledVocabularyParameterOrBuilder>
      getAttributesOrBuilderList();
  /**
   * <pre>
   * additional user defined attributes that describe ADC channels
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 2;</code>
   */
  ControlledVocabularyParameterOrBuilder getAttributesOrBuilder(
      int index);
}
