/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * Scan or acquisition from original raw file 
 * used to create this peak list, as specified in sourceFile.
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.BinaryData}
 */
@com.google.protobuf.Generated
public final class BinaryData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.BinaryData)
    BinaryDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "BinaryData");
  }
  // Use BinaryData.newBuilder() to construct.
  private BinaryData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BinaryData() {
    attributes_ = java.util.Collections.emptyList();
    values_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_BinaryData_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_BinaryData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BinaryData.class, Builder.class);
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ControlledVocabularyParameter> attributes_;
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  @Override
  public java.util.List<ControlledVocabularyParameter> getAttributesList() {
    return attributes_;
  }
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  @Override
  public java.util.List<? extends ControlledVocabularyParameterOrBuilder>
      getAttributesOrBuilderList() {
    return attributes_;
  }
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  @Override
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  @Override
  public ControlledVocabularyParameter getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <pre>
   * attributes describing the values
   * for example: the following will be provided
   * MS:1000523 64-bit float
   * MS:1000514 m/z array OR MS:1000515 intensity array
   * optional MS:1000574 zlib compression
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
   */
  @Override
  public ControlledVocabularyParameterOrBuilder getAttributesOrBuilder(
      int index) {
    return attributes_.get(index);
  }

  public static final int VALUES_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString values_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * the values in a binary format 
   * </pre>
   *
   * <code>bytes Values = 2;</code>
   * @return The values.
   */
  @Override
  public com.google.protobuf.ByteString getValues() {
    return values_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < attributes_.size(); i++) {
      output.writeMessage(1, attributes_.get(i));
    }
    if (!values_.isEmpty()) {
      output.writeBytes(2, values_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < attributes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, attributes_.get(i));
    }
    if (!values_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, values_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BinaryData)) {
      return super.equals(obj);
    }
    BinaryData other = (BinaryData) obj;

    if (!getAttributesList()
        .equals(other.getAttributesList())) return false;
    if (!getValues()
        .equals(other.getValues())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAttributesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesList().hashCode();
    }
    hash = (37 * hash) + VALUES_FIELD_NUMBER;
    hash = (53 * hash) + getValues().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BinaryData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BinaryData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BinaryData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BinaryData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BinaryData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BinaryData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BinaryData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BinaryData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static BinaryData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static BinaryData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BinaryData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static BinaryData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BinaryData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Scan or acquisition from original raw file 
   * used to create this peak list, as specified in sourceFile.
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.BinaryData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.BinaryData)
      BinaryDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_BinaryData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_BinaryData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BinaryData.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.BinaryData.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
      } else {
        attributes_ = null;
        attributesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      values_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_BinaryData_descriptor;
    }

    @Override
    public BinaryData getDefaultInstanceForType() {
      return BinaryData.getDefaultInstance();
    }

    @Override
    public BinaryData build() {
      BinaryData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BinaryData buildPartial() {
      BinaryData result = new BinaryData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(BinaryData result) {
      if (attributesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.attributes_ = attributes_;
      } else {
        result.attributes_ = attributesBuilder_.build();
      }
    }

    private void buildPartial0(BinaryData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.values_ = values_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BinaryData) {
        return mergeFrom((BinaryData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BinaryData other) {
      if (other == BinaryData.getDefaultInstance()) return this;
      if (attributesBuilder_ == null) {
        if (!other.attributes_.isEmpty()) {
          if (attributes_.isEmpty()) {
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAttributesIsMutable();
            attributes_.addAll(other.attributes_);
          }
          onChanged();
        }
      } else {
        if (!other.attributes_.isEmpty()) {
          if (attributesBuilder_.isEmpty()) {
            attributesBuilder_.dispose();
            attributesBuilder_ = null;
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            attributesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAttributesFieldBuilder() : null;
          } else {
            attributesBuilder_.addAllMessages(other.attributes_);
          }
        }
      }
      if (!other.getValues().isEmpty()) {
        setValues(other.getValues());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ControlledVocabularyParameter m =
                  input.readMessage(
                      ControlledVocabularyParameter.parser(),
                      extensionRegistry);
              if (attributesBuilder_ == null) {
                ensureAttributesIsMutable();
                attributes_.add(m);
              } else {
                attributesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              values_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ControlledVocabularyParameter> attributes_ =
      java.util.Collections.emptyList();
    private void ensureAttributesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        attributes_ = new java.util.ArrayList<ControlledVocabularyParameter>(attributes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ControlledVocabularyParameter, ControlledVocabularyParameter.Builder, ControlledVocabularyParameterOrBuilder> attributesBuilder_;

    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public java.util.List<ControlledVocabularyParameter> getAttributesList() {
      if (attributesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributes_);
      } else {
        return attributesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public int getAttributesCount() {
      if (attributesBuilder_ == null) {
        return attributes_.size();
      } else {
        return attributesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public ControlledVocabularyParameter getAttributes(int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);
      } else {
        return attributesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder setAttributes(
        int index, ControlledVocabularyParameter value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.set(index, value);
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder setAttributes(
        int index, ControlledVocabularyParameter.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder addAttributes(ControlledVocabularyParameter value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder addAttributes(
        int index, ControlledVocabularyParameter value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(index, value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder addAttributes(
        ControlledVocabularyParameter.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder addAttributes(
        int index, ControlledVocabularyParameter.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder addAllAttributes(
        Iterable<? extends ControlledVocabularyParameter> values) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributes_);
        onChanged();
      } else {
        attributesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder clearAttributes() {
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        attributesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public Builder removeAttributes(int index) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.remove(index);
        onChanged();
      } else {
        attributesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public ControlledVocabularyParameter.Builder getAttributesBuilder(
        int index) {
      return internalGetAttributesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public ControlledVocabularyParameterOrBuilder getAttributesOrBuilder(
        int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);  } else {
        return attributesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public java.util.List<? extends ControlledVocabularyParameterOrBuilder>
         getAttributesOrBuilderList() {
      if (attributesBuilder_ != null) {
        return attributesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributes_);
      }
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public ControlledVocabularyParameter.Builder addAttributesBuilder() {
      return internalGetAttributesFieldBuilder().addBuilder(
          ControlledVocabularyParameter.getDefaultInstance());
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public ControlledVocabularyParameter.Builder addAttributesBuilder(
        int index) {
      return internalGetAttributesFieldBuilder().addBuilder(
          index, ControlledVocabularyParameter.getDefaultInstance());
    }
    /**
     * <pre>
     * attributes describing the values
     * for example: the following will be provided
     * MS:1000523 64-bit float
     * MS:1000514 m/z array OR MS:1000515 intensity array
     * optional MS:1000574 zlib compression
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter Attributes = 1;</code>
     */
    public java.util.List<ControlledVocabularyParameter.Builder>
         getAttributesBuilderList() {
      return internalGetAttributesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ControlledVocabularyParameter, ControlledVocabularyParameter.Builder, ControlledVocabularyParameterOrBuilder>
        internalGetAttributesFieldBuilder() {
      if (attributesBuilder_ == null) {
        attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ControlledVocabularyParameter, ControlledVocabularyParameter.Builder, ControlledVocabularyParameterOrBuilder>(
                attributes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        attributes_ = null;
      }
      return attributesBuilder_;
    }

    private com.google.protobuf.ByteString values_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * the values in a binary format 
     * </pre>
     *
     * <code>bytes Values = 2;</code>
     * @return The values.
     */
    @Override
    public com.google.protobuf.ByteString getValues() {
      return values_;
    }
    /**
     * <pre>
     * the values in a binary format 
     * </pre>
     *
     * <code>bytes Values = 2;</code>
     * @param value The values to set.
     * @return This builder for chaining.
     */
    public Builder setValues(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      values_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the values in a binary format 
     * </pre>
     *
     * <code>bytes Values = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValues() {
      bitField0_ = (bitField0_ & ~0x00000002);
      values_ = getDefaultInstance().getValues();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.BinaryData)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.BinaryData)
  private static final BinaryData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BinaryData();
  }

  public static BinaryData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinaryData>
      PARSER = new com.google.protobuf.AbstractParser<BinaryData>() {
    @Override
    public BinaryData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BinaryData> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BinaryData> getParserForType() {
    return PARSER;
  }

  @Override
  public BinaryData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

