/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy}
 */
@com.google.protobuf.Generated
public final class CollisionEnergy extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy)
    CollisionEnergyOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "CollisionEnergy");
  }
  // Use CollisionEnergy.newBuilder() to construct.
  private CollisionEnergy(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CollisionEnergy() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_CollisionEnergy_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_CollisionEnergy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CollisionEnergy.class, Builder.class);
  }

  public static final int COLLISIONENERGYRAMPSTART_FIELD_NUMBER = 1;
  private double collisionEnergyRampStart_ = 0D;
  /**
   * <pre>
   * Collision energy at the start of the collision energy ramp. see MS_1002013
   * </pre>
   *
   * <code>double CollisionEnergyRampStart = 1;</code>
   * @return The collisionEnergyRampStart.
   */
  @Override
  public double getCollisionEnergyRampStart() {
    return collisionEnergyRampStart_;
  }

  public static final int COLLISIONENERGYRAMPEND_FIELD_NUMBER = 2;
  private double collisionEnergyRampEnd_ = 0D;
  /**
   * <pre>
   * Collision energy at the end of the collision energy ramp. see MS_1002014
   * </pre>
   *
   * <code>double CollisionEnergyRampEnd = 2;</code>
   * @return The collisionEnergyRampEnd.
   */
  @Override
  public double getCollisionEnergyRampEnd() {
    return collisionEnergyRampEnd_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (Double.doubleToRawLongBits(collisionEnergyRampStart_) != 0) {
      output.writeDouble(1, collisionEnergyRampStart_);
    }
    if (Double.doubleToRawLongBits(collisionEnergyRampEnd_) != 0) {
      output.writeDouble(2, collisionEnergyRampEnd_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (Double.doubleToRawLongBits(collisionEnergyRampStart_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, collisionEnergyRampStart_);
    }
    if (Double.doubleToRawLongBits(collisionEnergyRampEnd_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, collisionEnergyRampEnd_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CollisionEnergy)) {
      return super.equals(obj);
    }
    CollisionEnergy other = (CollisionEnergy) obj;

    if (Double.doubleToLongBits(getCollisionEnergyRampStart())
        != Double.doubleToLongBits(
            other.getCollisionEnergyRampStart())) return false;
    if (Double.doubleToLongBits(getCollisionEnergyRampEnd())
        != Double.doubleToLongBits(
            other.getCollisionEnergyRampEnd())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLLISIONENERGYRAMPSTART_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCollisionEnergyRampStart()));
    hash = (37 * hash) + COLLISIONENERGYRAMPEND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCollisionEnergyRampEnd()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CollisionEnergy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CollisionEnergy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CollisionEnergy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CollisionEnergy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CollisionEnergy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CollisionEnergy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CollisionEnergy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CollisionEnergy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CollisionEnergy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CollisionEnergy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CollisionEnergy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CollisionEnergy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CollisionEnergy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy)
      CollisionEnergyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_CollisionEnergy_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_CollisionEnergy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CollisionEnergy.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.CollisionEnergy.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      collisionEnergyRampStart_ = 0D;
      collisionEnergyRampEnd_ = 0D;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_CollisionEnergy_descriptor;
    }

    @Override
    public CollisionEnergy getDefaultInstanceForType() {
      return CollisionEnergy.getDefaultInstance();
    }

    @Override
    public CollisionEnergy build() {
      CollisionEnergy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CollisionEnergy buildPartial() {
      CollisionEnergy result = new CollisionEnergy(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CollisionEnergy result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.collisionEnergyRampStart_ = collisionEnergyRampStart_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.collisionEnergyRampEnd_ = collisionEnergyRampEnd_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CollisionEnergy) {
        return mergeFrom((CollisionEnergy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CollisionEnergy other) {
      if (other == CollisionEnergy.getDefaultInstance()) return this;
      if (Double.doubleToRawLongBits(other.getCollisionEnergyRampStart()) != 0) {
        setCollisionEnergyRampStart(other.getCollisionEnergyRampStart());
      }
      if (Double.doubleToRawLongBits(other.getCollisionEnergyRampEnd()) != 0) {
        setCollisionEnergyRampEnd(other.getCollisionEnergyRampEnd());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              collisionEnergyRampStart_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              collisionEnergyRampEnd_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double collisionEnergyRampStart_ ;
    /**
     * <pre>
     * Collision energy at the start of the collision energy ramp. see MS_1002013
     * </pre>
     *
     * <code>double CollisionEnergyRampStart = 1;</code>
     * @return The collisionEnergyRampStart.
     */
    @Override
    public double getCollisionEnergyRampStart() {
      return collisionEnergyRampStart_;
    }
    /**
     * <pre>
     * Collision energy at the start of the collision energy ramp. see MS_1002013
     * </pre>
     *
     * <code>double CollisionEnergyRampStart = 1;</code>
     * @param value The collisionEnergyRampStart to set.
     * @return This builder for chaining.
     */
    public Builder setCollisionEnergyRampStart(double value) {

      collisionEnergyRampStart_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Collision energy at the start of the collision energy ramp. see MS_1002013
     * </pre>
     *
     * <code>double CollisionEnergyRampStart = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollisionEnergyRampStart() {
      bitField0_ = (bitField0_ & ~0x00000001);
      collisionEnergyRampStart_ = 0D;
      onChanged();
      return this;
    }

    private double collisionEnergyRampEnd_ ;
    /**
     * <pre>
     * Collision energy at the end of the collision energy ramp. see MS_1002014
     * </pre>
     *
     * <code>double CollisionEnergyRampEnd = 2;</code>
     * @return The collisionEnergyRampEnd.
     */
    @Override
    public double getCollisionEnergyRampEnd() {
      return collisionEnergyRampEnd_;
    }
    /**
     * <pre>
     * Collision energy at the end of the collision energy ramp. see MS_1002014
     * </pre>
     *
     * <code>double CollisionEnergyRampEnd = 2;</code>
     * @param value The collisionEnergyRampEnd to set.
     * @return This builder for chaining.
     */
    public Builder setCollisionEnergyRampEnd(double value) {

      collisionEnergyRampEnd_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Collision energy at the end of the collision energy ramp. see MS_1002014
     * </pre>
     *
     * <code>double CollisionEnergyRampEnd = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollisionEnergyRampEnd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      collisionEnergyRampEnd_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.CollisionEnergy)
  private static final CollisionEnergy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CollisionEnergy();
  }

  public static CollisionEnergy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CollisionEnergy>
      PARSER = new com.google.protobuf.AbstractParser<CollisionEnergy>() {
    @Override
    public CollisionEnergy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CollisionEnergy> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CollisionEnergy> getParserForType() {
    return PARSER;
  }

  @Override
  public CollisionEnergy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

