/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface ControlledVocabularyParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.ControlledVocabularyParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The accession number of the referred-to 
   * term in the named resource (e.g.: MS:000012).
   * </pre>
   *
   * <code>string Accession = 1;</code>
   * @return The accession.
   */
  String getAccession();
  /**
   * <pre>
   * The accession number of the referred-to 
   * term in the named resource (e.g.: MS:000012).
   * </pre>
   *
   * <code>string Accession = 1;</code>
   * @return The bytes for accession.
   */
  com.google.protobuf.ByteString
      getAccessionBytes();

  /**
   * <pre>
   * The actual name for the parameter, from
   * the referred-to controlled vocabulary. This should be 
   * the preferred name associated with the specified accession
   * number.
   * </pre>
   *
   * <code>string Name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * The actual name for the parameter, from
   * the referred-to controlled vocabulary. This should be 
   * the preferred name associated with the specified accession
   * number.
   * </pre>
   *
   * <code>string Name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * the value
   * </pre>
   *
   * <code>string Value = 3;</code>
   * @return The value.
   */
  String getValue();
  /**
   * <pre>
   * the value
   * </pre>
   *
   * <code>string Value = 3;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
