/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * represents the request to extract the stream of MRM xic descriptors
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest}
 */
@com.google.protobuf.Generated
public final class GetMrmXicRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest)
    GetMrmXicRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "GetMrmXicRequest");
  }
  // Use GetMrmXicRequest.newBuilder() to construct.
  private GetMrmXicRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetMrmXicRequest() {
    sampleId_ = "";
    experimentId_ = "";
    massIndexes_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetMrmXicRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetMrmXicRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetMrmXicRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int SAMPLEID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object sampleId_ = "";
  /**
   * <pre>
   * the id of the sample 
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The sampleId.
   */
  @Override
  public String getSampleId() {
    Object ref = sampleId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sampleId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the id of the sample 
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The bytes for sampleId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSampleIdBytes() {
    Object ref = sampleId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sampleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERIMENTID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object experimentId_ = "";
  /**
   * <pre>
   * &#47; the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  @Override
  public String getExperimentId() {
    Object ref = experimentId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      experimentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#47; the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  @Override
  public com.google.protobuf.ByteString
      getExperimentIdBytes() {
    Object ref = experimentId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      experimentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MASSINDEXES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList massIndexes_ =
      emptyIntList();
  /**
   * <pre>
   * &#47; the list of mass indices
   * </pre>
   *
   * <code>repeated int32 MassIndexes = 3;</code>
   * @return A list containing the massIndexes.
   */
  @Override
  public java.util.List<Integer>
      getMassIndexesList() {
    return massIndexes_;
  }
  /**
   * <pre>
   * &#47; the list of mass indices
   * </pre>
   *
   * <code>repeated int32 MassIndexes = 3;</code>
   * @return The count of massIndexes.
   */
  public int getMassIndexesCount() {
    return massIndexes_.size();
  }
  /**
   * <pre>
   * &#47; the list of mass indices
   * </pre>
   *
   * <code>repeated int32 MassIndexes = 3;</code>
   * @param index The index of the element to return.
   * @return The massIndexes at the given index.
   */
  public int getMassIndexes(int index) {
    return massIndexes_.getInt(index);
  }
  private int massIndexesMemoizedSerializedSize = -1;

  public static final int CYCLERANGE_FIELD_NUMBER = 4;
  private CycleRange cycleRange_;
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   * @return Whether the cycleRange field is set.
   */
  @Override
  public boolean hasCycleRange() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   * @return The cycleRange.
   */
  @Override
  public CycleRange getCycleRange() {
    return cycleRange_ == null ? CycleRange.getDefaultInstance() : cycleRange_;
  }
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   */
  @Override
  public CycleRangeOrBuilder getCycleRangeOrBuilder() {
    return cycleRange_ == null ? CycleRange.getDefaultInstance() : cycleRange_;
  }

  public static final int TIMERANGE_FIELD_NUMBER = 5;
  private TimeRange timeRange_;
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   * @return Whether the timeRange field is set.
   */
  @Override
  public boolean hasTimeRange() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   * @return The timeRange.
   */
  @Override
  public TimeRange getTimeRange() {
    return timeRange_ == null ? TimeRange.getDefaultInstance() : timeRange_;
  }
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   */
  @Override
  public TimeRangeOrBuilder getTimeRangeOrBuilder() {
    return timeRange_ == null ? TimeRange.getDefaultInstance() : timeRange_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sampleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, experimentId_);
    }
    if (getMassIndexesList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(massIndexesMemoizedSerializedSize);
    }
    for (int i = 0; i < massIndexes_.size(); i++) {
      output.writeInt32NoTag(massIndexes_.getInt(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getCycleRange());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getTimeRange());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sampleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, experimentId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < massIndexes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(massIndexes_.getInt(i));
      }
      size += dataSize;
      if (!getMassIndexesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      massIndexesMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCycleRange());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTimeRange());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetMrmXicRequest)) {
      return super.equals(obj);
    }
    GetMrmXicRequest other = (GetMrmXicRequest) obj;

    if (!getSampleId()
        .equals(other.getSampleId())) return false;
    if (!getExperimentId()
        .equals(other.getExperimentId())) return false;
    if (!getMassIndexesList()
        .equals(other.getMassIndexesList())) return false;
    if (hasCycleRange() != other.hasCycleRange()) return false;
    if (hasCycleRange()) {
      if (!getCycleRange()
          .equals(other.getCycleRange())) return false;
    }
    if (hasTimeRange() != other.hasTimeRange()) return false;
    if (hasTimeRange()) {
      if (!getTimeRange()
          .equals(other.getTimeRange())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SAMPLEID_FIELD_NUMBER;
    hash = (53 * hash) + getSampleId().hashCode();
    hash = (37 * hash) + EXPERIMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getExperimentId().hashCode();
    if (getMassIndexesCount() > 0) {
      hash = (37 * hash) + MASSINDEXES_FIELD_NUMBER;
      hash = (53 * hash) + getMassIndexesList().hashCode();
    }
    if (hasCycleRange()) {
      hash = (37 * hash) + CYCLERANGE_FIELD_NUMBER;
      hash = (53 * hash) + getCycleRange().hashCode();
    }
    if (hasTimeRange()) {
      hash = (37 * hash) + TIMERANGE_FIELD_NUMBER;
      hash = (53 * hash) + getTimeRange().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetMrmXicRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetMrmXicRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetMrmXicRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetMrmXicRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetMrmXicRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetMrmXicRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetMrmXicRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static GetMrmXicRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static GetMrmXicRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static GetMrmXicRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetMrmXicRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static GetMrmXicRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetMrmXicRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * represents the request to extract the stream of MRM xic descriptors
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest)
      GetMrmXicRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetMrmXicRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetMrmXicRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetMrmXicRequest.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.GetMrmXicRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCycleRangeFieldBuilder();
        internalGetTimeRangeFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sampleId_ = "";
      experimentId_ = "";
      massIndexes_ = emptyIntList();
      cycleRange_ = null;
      if (cycleRangeBuilder_ != null) {
        cycleRangeBuilder_.dispose();
        cycleRangeBuilder_ = null;
      }
      timeRange_ = null;
      if (timeRangeBuilder_ != null) {
        timeRangeBuilder_.dispose();
        timeRangeBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetMrmXicRequest_descriptor;
    }

    @Override
    public GetMrmXicRequest getDefaultInstanceForType() {
      return GetMrmXicRequest.getDefaultInstance();
    }

    @Override
    public GetMrmXicRequest build() {
      GetMrmXicRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetMrmXicRequest buildPartial() {
      GetMrmXicRequest result = new GetMrmXicRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(GetMrmXicRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sampleId_ = sampleId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.experimentId_ = experimentId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        massIndexes_.makeImmutable();
        result.massIndexes_ = massIndexes_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cycleRange_ = cycleRangeBuilder_ == null
            ? cycleRange_
            : cycleRangeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timeRange_ = timeRangeBuilder_ == null
            ? timeRange_
            : timeRangeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetMrmXicRequest) {
        return mergeFrom((GetMrmXicRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetMrmXicRequest other) {
      if (other == GetMrmXicRequest.getDefaultInstance()) return this;
      if (!other.getSampleId().isEmpty()) {
        sampleId_ = other.sampleId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getExperimentId().isEmpty()) {
        experimentId_ = other.experimentId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.massIndexes_.isEmpty()) {
        if (massIndexes_.isEmpty()) {
          massIndexes_ = other.massIndexes_;
          massIndexes_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureMassIndexesIsMutable();
          massIndexes_.addAll(other.massIndexes_);
        }
        onChanged();
      }
      if (other.hasCycleRange()) {
        mergeCycleRange(other.getCycleRange());
      }
      if (other.hasTimeRange()) {
        mergeTimeRange(other.getTimeRange());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sampleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              experimentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              int v = input.readInt32();
              ensureMassIndexesIsMutable();
              massIndexes_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureMassIndexesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                massIndexes_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetCycleRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetTimeRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object sampleId_ = "";
    /**
     * <pre>
     * the id of the sample 
     * </pre>
     *
     * <code>string SampleId = 1;</code>
     * @return The sampleId.
     */
    public String getSampleId() {
      Object ref = sampleId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sampleId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * the id of the sample 
     * </pre>
     *
     * <code>string SampleId = 1;</code>
     * @return The bytes for sampleId.
     */
    public com.google.protobuf.ByteString
        getSampleIdBytes() {
      Object ref = sampleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sampleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the id of the sample 
     * </pre>
     *
     * <code>string SampleId = 1;</code>
     * @param value The sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      sampleId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the sample 
     * </pre>
     *
     * <code>string SampleId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleId() {
      sampleId_ = getDefaultInstance().getSampleId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the sample 
     * </pre>
     *
     * <code>string SampleId = 1;</code>
     * @param value The bytes for sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sampleId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object experimentId_ = "";
    /**
     * <pre>
     * &#47; the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @return The experimentId.
     */
    public String getExperimentId() {
      Object ref = experimentId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        experimentId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * &#47; the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @return The bytes for experimentId.
     */
    public com.google.protobuf.ByteString
        getExperimentIdBytes() {
      Object ref = experimentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        experimentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#47; the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @param value The experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      experimentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExperimentId() {
      experimentId_ = getDefaultInstance().getExperimentId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 2;</code>
     * @param value The bytes for experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      experimentId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList massIndexes_ = emptyIntList();
    private void ensureMassIndexesIsMutable() {
      if (!massIndexes_.isModifiable()) {
        massIndexes_ = makeMutableCopy(massIndexes_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @return A list containing the massIndexes.
     */
    public java.util.List<Integer>
        getMassIndexesList() {
      massIndexes_.makeImmutable();
      return massIndexes_;
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @return The count of massIndexes.
     */
    public int getMassIndexesCount() {
      return massIndexes_.size();
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @param index The index of the element to return.
     * @return The massIndexes at the given index.
     */
    public int getMassIndexes(int index) {
      return massIndexes_.getInt(index);
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @param index The index to set the value at.
     * @param value The massIndexes to set.
     * @return This builder for chaining.
     */
    public Builder setMassIndexes(
        int index, int value) {

      ensureMassIndexesIsMutable();
      massIndexes_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @param value The massIndexes to add.
     * @return This builder for chaining.
     */
    public Builder addMassIndexes(int value) {

      ensureMassIndexesIsMutable();
      massIndexes_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @param values The massIndexes to add.
     * @return This builder for chaining.
     */
    public Builder addAllMassIndexes(
        Iterable<? extends Integer> values) {
      ensureMassIndexesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, massIndexes_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the list of mass indices
     * </pre>
     *
     * <code>repeated int32 MassIndexes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMassIndexes() {
      massIndexes_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private CycleRange cycleRange_;
    private com.google.protobuf.SingleFieldBuilder<
        CycleRange, CycleRange.Builder, CycleRangeOrBuilder> cycleRangeBuilder_;
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     * @return Whether the cycleRange field is set.
     */
    public boolean hasCycleRange() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     * @return The cycleRange.
     */
    public CycleRange getCycleRange() {
      if (cycleRangeBuilder_ == null) {
        return cycleRange_ == null ? CycleRange.getDefaultInstance() : cycleRange_;
      } else {
        return cycleRangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    public Builder setCycleRange(CycleRange value) {
      if (cycleRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cycleRange_ = value;
      } else {
        cycleRangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    public Builder setCycleRange(
        CycleRange.Builder builderForValue) {
      if (cycleRangeBuilder_ == null) {
        cycleRange_ = builderForValue.build();
      } else {
        cycleRangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    public Builder mergeCycleRange(CycleRange value) {
      if (cycleRangeBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          cycleRange_ != null &&
          cycleRange_ != CycleRange.getDefaultInstance()) {
          getCycleRangeBuilder().mergeFrom(value);
        } else {
          cycleRange_ = value;
        }
      } else {
        cycleRangeBuilder_.mergeFrom(value);
      }
      if (cycleRange_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    public Builder clearCycleRange() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cycleRange_ = null;
      if (cycleRangeBuilder_ != null) {
        cycleRangeBuilder_.dispose();
        cycleRangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    public CycleRange.Builder getCycleRangeBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetCycleRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    public CycleRangeOrBuilder getCycleRangeOrBuilder() {
      if (cycleRangeBuilder_ != null) {
        return cycleRangeBuilder_.getMessageOrBuilder();
      } else {
        return cycleRange_ == null ?
            CycleRange.getDefaultInstance() : cycleRange_;
      }
    }
    /**
     * <pre>
     * &#47; the range of cycles
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        CycleRange, CycleRange.Builder, CycleRangeOrBuilder>
        internalGetCycleRangeFieldBuilder() {
      if (cycleRangeBuilder_ == null) {
        cycleRangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            CycleRange, CycleRange.Builder, CycleRangeOrBuilder>(
                getCycleRange(),
                getParentForChildren(),
                isClean());
        cycleRange_ = null;
      }
      return cycleRangeBuilder_;
    }

    private TimeRange timeRange_;
    private com.google.protobuf.SingleFieldBuilder<
        TimeRange, TimeRange.Builder, TimeRangeOrBuilder> timeRangeBuilder_;
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     * @return Whether the timeRange field is set.
     */
    public boolean hasTimeRange() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     * @return The timeRange.
     */
    public TimeRange getTimeRange() {
      if (timeRangeBuilder_ == null) {
        return timeRange_ == null ? TimeRange.getDefaultInstance() : timeRange_;
      } else {
        return timeRangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    public Builder setTimeRange(TimeRange value) {
      if (timeRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeRange_ = value;
      } else {
        timeRangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    public Builder setTimeRange(
        TimeRange.Builder builderForValue) {
      if (timeRangeBuilder_ == null) {
        timeRange_ = builderForValue.build();
      } else {
        timeRangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    public Builder mergeTimeRange(TimeRange value) {
      if (timeRangeBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          timeRange_ != null &&
          timeRange_ != TimeRange.getDefaultInstance()) {
          getTimeRangeBuilder().mergeFrom(value);
        } else {
          timeRange_ = value;
        }
      } else {
        timeRangeBuilder_.mergeFrom(value);
      }
      if (timeRange_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    public Builder clearTimeRange() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timeRange_ = null;
      if (timeRangeBuilder_ != null) {
        timeRangeBuilder_.dispose();
        timeRangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    public TimeRange.Builder getTimeRangeBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetTimeRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    public TimeRangeOrBuilder getTimeRangeOrBuilder() {
      if (timeRangeBuilder_ != null) {
        return timeRangeBuilder_.getMessageOrBuilder();
      } else {
        return timeRange_ == null ?
            TimeRange.getDefaultInstance() : timeRange_;
      }
    }
    /**
     * <pre>
     * &#47; the range of the time
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        TimeRange, TimeRange.Builder, TimeRangeOrBuilder>
        internalGetTimeRangeFieldBuilder() {
      if (timeRangeBuilder_ == null) {
        timeRangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            TimeRange, TimeRange.Builder, TimeRangeOrBuilder>(
                getTimeRange(),
                getParentForChildren(),
                isClean());
        timeRange_ = null;
      }
      return timeRangeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.GetMrmXicRequest)
  private static final GetMrmXicRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetMrmXicRequest();
  }

  public static GetMrmXicRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMrmXicRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetMrmXicRequest>() {
    @Override
    public GetMrmXicRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetMrmXicRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetMrmXicRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public GetMrmXicRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

