/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * represents the request to extract stream of spectra for specific experiment
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest}
 */
@com.google.protobuf.Generated
public final class GetSpectraRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest)
    GetSpectraRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "GetSpectraRequest");
  }
  // Use GetSpectraRequest.newBuilder() to construct.
  private GetSpectraRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetSpectraRequest() {
    sampleId_ = "";
    experimentId_ = "";
    centroidOption_ = 0;
    smoothingOption_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetSpectraRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetSpectraRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetSpectraRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int RANGE_FIELD_NUMBER = 1;
  private TimeRange range_;
  /**
   * <pre>
   * This is a time window for sub selecting a subset of information 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   * @return Whether the range field is set.
   */
  @Override
  public boolean hasRange() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * This is a time window for sub selecting a subset of information 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   * @return The range.
   */
  @Override
  public TimeRange getRange() {
    return range_ == null ? TimeRange.getDefaultInstance() : range_;
  }
  /**
   * <pre>
   * This is a time window for sub selecting a subset of information 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   */
  @Override
  public TimeRangeOrBuilder getRangeOrBuilder() {
    return range_ == null ? TimeRange.getDefaultInstance() : range_;
  }

  public static final int SAMPLEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object sampleId_ = "";
  /**
   * <pre>
   * the id of the sample
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The sampleId.
   */
  @Override
  public String getSampleId() {
    Object ref = sampleId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sampleId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the id of the sample
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSampleIdBytes() {
    Object ref = sampleId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sampleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERIMENTID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object experimentId_ = "";
  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 3;</code>
   * @return The experimentId.
   */
  @Override
  public String getExperimentId() {
    Object ref = experimentId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      experimentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 3;</code>
   * @return The bytes for experimentId.
   */
  @Override
  public com.google.protobuf.ByteString
      getExperimentIdBytes() {
    Object ref = experimentId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      experimentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONVERTTOCENTROID_FIELD_NUMBER = 4;
  private boolean convertToCentroid_ = false;
  /**
   * <pre>
   * if true then the data is returned in the Centroid format (i.e. it will be processed using spectral peaks finder)
   * </pre>
   *
   * <code>bool ConvertToCentroid = 4;</code>
   * @return The convertToCentroid.
   */
  @Override
  public boolean getConvertToCentroid() {
    return convertToCentroid_;
  }

  public static final int ADDFRAMINGZEROS_FIELD_NUMBER = 5;
  private int addFramingZeros_ = 0;
  /**
   * <pre>
   * if the value is greater than 0 process the data to add framing zeros 
   * (data will be processed - this operation incurs overhead)
   * default 1
   * </pre>
   *
   * <code>int32 AddFramingZeros = 5;</code>
   * @return The addFramingZeros.
   */
  @Override
  public int getAddFramingZeros() {
    return addFramingZeros_;
  }

  public static final int OVERRIDEADDFRAMINGZEROSDEFAULTVALUE_FIELD_NUMBER = 6;
  private boolean overrideAddFramingZerosDefaultValue_ = false;
  /**
   * <pre>
   * This flag when set to false will set the framing zeros to one
   * </pre>
   *
   * <code>bool OverrideAddFramingZerosDefaultValue = 6;</code>
   * @return The overrideAddFramingZerosDefaultValue.
   */
  @Override
  public boolean getOverrideAddFramingZerosDefaultValue() {
    return overrideAddFramingZerosDefaultValue_;
  }

  public static final int CENTROIDOPTION_FIELD_NUMBER = 7;
  private int centroidOption_ = 0;
  /**
   * <pre>
   * This metric specifies which peak metric should be returned as the y-values when centroiding.
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
   * @return Whether the centroidOption field is set.
   */
  @Override public boolean hasCentroidOption() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * This metric specifies which peak metric should be returned as the y-values when centroiding.
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
   * @return The enum numeric value on the wire for centroidOption.
   */
  @Override public int getCentroidOptionValue() {
    return centroidOption_;
  }
  /**
   * <pre>
   * This metric specifies which peak metric should be returned as the y-values when centroiding.
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
   * @return The centroidOption.
   */
  @Override public CentroidOptions getCentroidOption() {
    CentroidOptions result = CentroidOptions.forNumber(centroidOption_);
    return result == null ? CentroidOptions.UNRECOGNIZED : result;
  }

  public static final int INCLUDEISOLATEDPOINTSASPEAKS_FIELD_NUMBER = 8;
  private boolean includeIsolatedPointsAsPeaks_ = false;

  /**
   * <pre>
   * Indicates whether to include isolated points as peaks.
   * </pre>
   *
   * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
   *
   * @return Whether the includeIsolatedPointsAsPeaks field is set.
   */
  @Override
  public boolean hasIncludeIsolatedPointsAsPeaks() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <pre>
   * Indicates whether to include isolated points as peaks.
   * </pre>
   *
   * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
   *
   * @return The includeIsolatedPointsAsPeaks.
   */
  @Override
  public boolean getIncludeIsolatedPointsAsPeaks() {
    return includeIsolatedPointsAsPeaks_;
  }

  public static final int SMOOTHINGOPTION_FIELD_NUMBER = 9;
  private int smoothingOption_ = 0;

  /**
   * <pre>
   * Data Smoothing
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
   * 9;</code>
   *
   * @return Whether the smoothingOption field is set.
   */
  @Override
  public boolean hasSmoothingOption() {
    return ((bitField0_ & 0x00000008) != 0);
  }

  /**
   * <pre>
   * Data Smoothing
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
   * 9;</code>
   *
   * @return The enum numeric value on the wire for smoothingOption.
   */
  @Override
  public int getSmoothingOptionValue() {
    return smoothingOption_;
  }

  /**
   * <pre>
   * Data Smoothing
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
   * 9;</code>
   *
   * @return The smoothingOption.
   */
  @Override
  public SmoothingOptions getSmoothingOption() {
    SmoothingOptions result = SmoothingOptions.forNumber(smoothingOption_);
    return result == null ? SmoothingOptions.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRange());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sampleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, experimentId_);
    }
    if (convertToCentroid_ != false) {
      output.writeBool(4, convertToCentroid_);
    }
    if (addFramingZeros_ != 0) {
      output.writeInt32(5, addFramingZeros_);
    }
    if (overrideAddFramingZerosDefaultValue_ != false) {
      output.writeBool(6, overrideAddFramingZerosDefaultValue_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(7, centroidOption_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(8, includeIsolatedPointsAsPeaks_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(9, smoothingOption_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRange());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sampleId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sampleId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(experimentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, experimentId_);
    }
    if (convertToCentroid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, convertToCentroid_);
    }
    if (addFramingZeros_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, addFramingZeros_);
    }
    if (overrideAddFramingZerosDefaultValue_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, overrideAddFramingZerosDefaultValue_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, centroidOption_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(8,
          includeIsolatedPointsAsPeaks_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(9, smoothingOption_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetSpectraRequest)) {
      return super.equals(obj);
    }
    GetSpectraRequest other = (GetSpectraRequest) obj;

    if (hasRange() != other.hasRange()) return false;
    if (hasRange()) {
      if (!getRange()
          .equals(other.getRange())) return false;
    }
    if (!getSampleId()
        .equals(other.getSampleId())) return false;
    if (!getExperimentId()
        .equals(other.getExperimentId())) return false;
    if (getConvertToCentroid()
        != other.getConvertToCentroid()) return false;
    if (getAddFramingZeros()
        != other.getAddFramingZeros()) return false;
    if (getOverrideAddFramingZerosDefaultValue()
        != other.getOverrideAddFramingZerosDefaultValue()) return false;
    if (hasCentroidOption() != other.hasCentroidOption()) return false;
    if (hasCentroidOption()) {
      if (centroidOption_ != other.centroidOption_)
        return false;
    }
    if (hasIncludeIsolatedPointsAsPeaks() != other.hasIncludeIsolatedPointsAsPeaks()) {
      return false;
    }
    if (hasIncludeIsolatedPointsAsPeaks()) {
      if (getIncludeIsolatedPointsAsPeaks() != other.getIncludeIsolatedPointsAsPeaks()) {
        return false;
      }
    }
    if (hasSmoothingOption() != other.hasSmoothingOption()) {
      return false;
    }
    if (hasSmoothingOption()) {
      if (smoothingOption_ != other.smoothingOption_) {
        return false;
      }
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRange()) {
      hash = (37 * hash) + RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getRange().hashCode();
    }
    hash = (37 * hash) + SAMPLEID_FIELD_NUMBER;
    hash = (53 * hash) + getSampleId().hashCode();
    hash = (37 * hash) + EXPERIMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getExperimentId().hashCode();
    hash = (37 * hash) + CONVERTTOCENTROID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getConvertToCentroid());
    hash = (37 * hash) + ADDFRAMINGZEROS_FIELD_NUMBER;
    hash = (53 * hash) + getAddFramingZeros();
    hash = (37 * hash) + OVERRIDEADDFRAMINGZEROSDEFAULTVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOverrideAddFramingZerosDefaultValue());
    if (hasCentroidOption()) {
      hash = (37 * hash) + CENTROIDOPTION_FIELD_NUMBER;
      hash = (53 * hash) + centroidOption_;
    }
    if (hasIncludeIsolatedPointsAsPeaks()) {
      hash = (37 * hash) + INCLUDEISOLATEDPOINTSASPEAKS_FIELD_NUMBER;
      hash =
          (53 * hash) + com.google.protobuf.Internal.hashBoolean(getIncludeIsolatedPointsAsPeaks());
    }
    if (hasSmoothingOption()) {
      hash = (37 * hash) + SMOOTHINGOPTION_FIELD_NUMBER;
      hash = (53 * hash) + smoothingOption_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetSpectraRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetSpectraRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetSpectraRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetSpectraRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetSpectraRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetSpectraRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetSpectraRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static GetSpectraRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static GetSpectraRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static GetSpectraRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetSpectraRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static GetSpectraRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetSpectraRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * represents the request to extract stream of spectra for specific experiment
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest)
      GetSpectraRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetSpectraRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetSpectraRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetSpectraRequest.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.GetSpectraRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRangeFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      range_ = null;
      if (rangeBuilder_ != null) {
        rangeBuilder_.dispose();
        rangeBuilder_ = null;
      }
      sampleId_ = "";
      experimentId_ = "";
      convertToCentroid_ = false;
      addFramingZeros_ = 0;
      overrideAddFramingZerosDefaultValue_ = false;
      centroidOption_ = 0;
      includeIsolatedPointsAsPeaks_ = false;
      smoothingOption_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_GetSpectraRequest_descriptor;
    }

    @Override
    public GetSpectraRequest getDefaultInstanceForType() {
      return GetSpectraRequest.getDefaultInstance();
    }

    @Override
    public GetSpectraRequest build() {
      GetSpectraRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GetSpectraRequest buildPartial() {
      GetSpectraRequest result = new GetSpectraRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(GetSpectraRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.range_ = rangeBuilder_ == null
            ? range_
            : rangeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sampleId_ = sampleId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.experimentId_ = experimentId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.convertToCentroid_ = convertToCentroid_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.addFramingZeros_ = addFramingZeros_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.overrideAddFramingZerosDefaultValue_ = overrideAddFramingZerosDefaultValue_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.centroidOption_ = centroidOption_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.includeIsolatedPointsAsPeaks_ = includeIsolatedPointsAsPeaks_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.smoothingOption_ = smoothingOption_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetSpectraRequest) {
        return mergeFrom((GetSpectraRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetSpectraRequest other) {
      if (other == GetSpectraRequest.getDefaultInstance()) return this;
      if (other.hasRange()) {
        mergeRange(other.getRange());
      }
      if (!other.getSampleId().isEmpty()) {
        sampleId_ = other.sampleId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getExperimentId().isEmpty()) {
        experimentId_ = other.experimentId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getConvertToCentroid() != false) {
        setConvertToCentroid(other.getConvertToCentroid());
      }
      if (other.getAddFramingZeros() != 0) {
        setAddFramingZeros(other.getAddFramingZeros());
      }
      if (other.getOverrideAddFramingZerosDefaultValue() != false) {
        setOverrideAddFramingZerosDefaultValue(other.getOverrideAddFramingZerosDefaultValue());
      }
      if (other.hasCentroidOption()) {
        setCentroidOptionValue(other.getCentroidOptionValue());
      }
      if (other.hasIncludeIsolatedPointsAsPeaks()) {
        setIncludeIsolatedPointsAsPeaks(other.getIncludeIsolatedPointsAsPeaks());
      }
      if (other.hasSmoothingOption()) {
        setSmoothingOptionValue(other.getSmoothingOptionValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sampleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              experimentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              convertToCentroid_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              addFramingZeros_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              overrideAddFramingZerosDefaultValue_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              centroidOption_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              includeIsolatedPointsAsPeaks_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              smoothingOption_ = input.readEnum();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private TimeRange range_;
    private com.google.protobuf.SingleFieldBuilder<
        TimeRange, TimeRange.Builder, TimeRangeOrBuilder> rangeBuilder_;
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     * @return Whether the range field is set.
     */
    public boolean hasRange() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     * @return The range.
     */
    public TimeRange getRange() {
      if (rangeBuilder_ == null) {
        return range_ == null ? TimeRange.getDefaultInstance() : range_;
      } else {
        return rangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    public Builder setRange(TimeRange value) {
      if (rangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        range_ = value;
      } else {
        rangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    public Builder setRange(
        TimeRange.Builder builderForValue) {
      if (rangeBuilder_ == null) {
        range_ = builderForValue.build();
      } else {
        rangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    public Builder mergeRange(TimeRange value) {
      if (rangeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          range_ != null &&
          range_ != TimeRange.getDefaultInstance()) {
          getRangeBuilder().mergeFrom(value);
        } else {
          range_ = value;
        }
      } else {
        rangeBuilder_.mergeFrom(value);
      }
      if (range_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    public Builder clearRange() {
      bitField0_ = (bitField0_ & ~0x00000001);
      range_ = null;
      if (rangeBuilder_ != null) {
        rangeBuilder_.dispose();
        rangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    public TimeRange.Builder getRangeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    public TimeRangeOrBuilder getRangeOrBuilder() {
      if (rangeBuilder_ != null) {
        return rangeBuilder_.getMessageOrBuilder();
      } else {
        return range_ == null ?
            TimeRange.getDefaultInstance() : range_;
      }
    }
    /**
     * <pre>
     * This is a time window for sub selecting a subset of information 
     * </pre>
     *
     * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        TimeRange, TimeRange.Builder, TimeRangeOrBuilder>
        internalGetRangeFieldBuilder() {
      if (rangeBuilder_ == null) {
        rangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            TimeRange, TimeRange.Builder, TimeRangeOrBuilder>(
                getRange(),
                getParentForChildren(),
                isClean());
        range_ = null;
      }
      return rangeBuilder_;
    }

    private Object sampleId_ = "";
    /**
     * <pre>
     * the id of the sample
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @return The sampleId.
     */
    public String getSampleId() {
      Object ref = sampleId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sampleId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * the id of the sample
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @return The bytes for sampleId.
     */
    public com.google.protobuf.ByteString
        getSampleIdBytes() {
      Object ref = sampleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sampleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the id of the sample
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @param value The sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      sampleId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the sample
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleId() {
      sampleId_ = getDefaultInstance().getSampleId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the sample
     * </pre>
     *
     * <code>string SampleId = 2;</code>
     * @param value The bytes for sampleId to set.
     * @return This builder for chaining.
     */
    public Builder setSampleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sampleId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object experimentId_ = "";
    /**
     * <pre>
     * the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 3;</code>
     * @return The experimentId.
     */
    public String getExperimentId() {
      Object ref = experimentId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        experimentId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 3;</code>
     * @return The bytes for experimentId.
     */
    public com.google.protobuf.ByteString
        getExperimentIdBytes() {
      Object ref = experimentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        experimentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 3;</code>
     * @param value The experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      experimentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExperimentId() {
      experimentId_ = getDefaultInstance().getExperimentId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the id of the experiment
     * </pre>
     *
     * <code>string ExperimentId = 3;</code>
     * @param value The bytes for experimentId to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      experimentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean convertToCentroid_ ;
    /**
     * <pre>
     * if true then the data is returned in the Centroid format (i.e. it will be processed using spectral peaks finder)
     * </pre>
     *
     * <code>bool ConvertToCentroid = 4;</code>
     * @return The convertToCentroid.
     */
    @Override
    public boolean getConvertToCentroid() {
      return convertToCentroid_;
    }
    /**
     * <pre>
     * if true then the data is returned in the Centroid format (i.e. it will be processed using spectral peaks finder)
     * </pre>
     *
     * <code>bool ConvertToCentroid = 4;</code>
     * @param value The convertToCentroid to set.
     * @return This builder for chaining.
     */
    public Builder setConvertToCentroid(boolean value) {

      convertToCentroid_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if true then the data is returned in the Centroid format (i.e. it will be processed using spectral peaks finder)
     * </pre>
     *
     * <code>bool ConvertToCentroid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConvertToCentroid() {
      bitField0_ = (bitField0_ & ~0x00000008);
      convertToCentroid_ = false;
      onChanged();
      return this;
    }

    private int addFramingZeros_ ;
    /**
     * <pre>
     * if the value is greater than 0 process the data to add framing zeros 
     * (data will be processed - this operation incurs overhead)
     * default 1
     * </pre>
     *
     * <code>int32 AddFramingZeros = 5;</code>
     * @return The addFramingZeros.
     */
    @Override
    public int getAddFramingZeros() {
      return addFramingZeros_;
    }
    /**
     * <pre>
     * if the value is greater than 0 process the data to add framing zeros 
     * (data will be processed - this operation incurs overhead)
     * default 1
     * </pre>
     *
     * <code>int32 AddFramingZeros = 5;</code>
     * @param value The addFramingZeros to set.
     * @return This builder for chaining.
     */
    public Builder setAddFramingZeros(int value) {

      addFramingZeros_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if the value is greater than 0 process the data to add framing zeros 
     * (data will be processed - this operation incurs overhead)
     * default 1
     * </pre>
     *
     * <code>int32 AddFramingZeros = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddFramingZeros() {
      bitField0_ = (bitField0_ & ~0x00000010);
      addFramingZeros_ = 0;
      onChanged();
      return this;
    }

    private boolean overrideAddFramingZerosDefaultValue_ ;
    /**
     * <pre>
     * This flag when set to false will set the framing zeros to one
     * </pre>
     *
     * <code>bool OverrideAddFramingZerosDefaultValue = 6;</code>
     * @return The overrideAddFramingZerosDefaultValue.
     */
    @Override
    public boolean getOverrideAddFramingZerosDefaultValue() {
      return overrideAddFramingZerosDefaultValue_;
    }
    /**
     * <pre>
     * This flag when set to false will set the framing zeros to one
     * </pre>
     *
     * <code>bool OverrideAddFramingZerosDefaultValue = 6;</code>
     * @param value The overrideAddFramingZerosDefaultValue to set.
     * @return This builder for chaining.
     */
    public Builder setOverrideAddFramingZerosDefaultValue(boolean value) {

      overrideAddFramingZerosDefaultValue_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This flag when set to false will set the framing zeros to one
     * </pre>
     *
     * <code>bool OverrideAddFramingZerosDefaultValue = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOverrideAddFramingZerosDefaultValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      overrideAddFramingZerosDefaultValue_ = false;
      onChanged();
      return this;
    }

    private int centroidOption_ = 0;
    /**
     * <pre>
     * This metric specifies which peak metric should be returned as the y-values when centroiding.
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
     * @return Whether the centroidOption field is set.
     */
    @Override public boolean hasCentroidOption() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * This metric specifies which peak metric should be returned as the y-values when centroiding.
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
     * @return The enum numeric value on the wire for centroidOption.
     */
    @Override public int getCentroidOptionValue() {
      return centroidOption_;
    }
    /**
     * <pre>
     * This metric specifies which peak metric should be returned as the y-values when centroiding.
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
     * @param value The enum numeric value on the wire for centroidOption to set.
     * @return This builder for chaining.
     */
    public Builder setCentroidOptionValue(int value) {
      centroidOption_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This metric specifies which peak metric should be returned as the y-values when centroiding.
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
     * @return The centroidOption.
     */
    @Override
    public CentroidOptions getCentroidOption() {
      CentroidOptions result = CentroidOptions.forNumber(centroidOption_);
      return result == null ? CentroidOptions.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * This metric specifies which peak metric should be returned as the y-values when centroiding.
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
     * @param value The centroidOption to set.
     * @return This builder for chaining.
     */
    public Builder setCentroidOption(CentroidOptions value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000040;
      centroidOption_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * This metric specifies which peak metric should be returned as the y-values when centroiding.
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCentroidOption() {
      bitField0_ = (bitField0_ & ~0x00000040);
      centroidOption_ = 0;
      onChanged();
      return this;
    }

    private boolean includeIsolatedPointsAsPeaks_;

    /**
     * <pre>
     * Indicates whether to include isolated points as peaks.
     * </pre>
     *
     * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
     *
     * @return Whether the includeIsolatedPointsAsPeaks field is set.
     */
    @Override
    public boolean hasIncludeIsolatedPointsAsPeaks() {
      return ((bitField0_ & 0x00000080) != 0);
    }

    /**
     * <pre>
     * Indicates whether to include isolated points as peaks.
     * </pre>
     *
     * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
     *
     * @return The includeIsolatedPointsAsPeaks.
     */
    @Override
    public boolean getIncludeIsolatedPointsAsPeaks() {
      return includeIsolatedPointsAsPeaks_;
    }

    /**
     * <pre>
     * Indicates whether to include isolated points as peaks.
     * </pre>
     *
     * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
     *
     * @param value The includeIsolatedPointsAsPeaks to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeIsolatedPointsAsPeaks(boolean value) {

      includeIsolatedPointsAsPeaks_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Indicates whether to include isolated points as peaks.
     * </pre>
     *
     * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearIncludeIsolatedPointsAsPeaks() {
      bitField0_ = (bitField0_ & ~0x00000080);
      includeIsolatedPointsAsPeaks_ = false;
      onChanged();
      return this;
    }

    private int smoothingOption_ = 0;

    /**
     * <pre>
     * Data Smoothing
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
     * 9;</code>
     *
     * @return Whether the smoothingOption field is set.
     */
    @Override
    public boolean hasSmoothingOption() {
      return ((bitField0_ & 0x00000100) != 0);
    }

    /**
     * <pre>
     * Data Smoothing
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
     * 9;</code>
     *
     * @return The enum numeric value on the wire for smoothingOption.
     */
    @Override
    public int getSmoothingOptionValue() {
      return smoothingOption_;
    }

    /**
     * <pre>
     * Data Smoothing
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
     * 9;</code>
     *
     * @param value The enum numeric value on the wire for smoothingOption to set.
     * @return This builder for chaining.
     */
    public Builder setSmoothingOptionValue(int value) {
      smoothingOption_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Data Smoothing
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
     * 9;</code>
     *
     * @return The smoothingOption.
     */
    @Override
    public SmoothingOptions getSmoothingOption() {
      SmoothingOptions result = SmoothingOptions.forNumber(smoothingOption_);
      return result == null ? SmoothingOptions.UNRECOGNIZED : result;
    }

    /**
     * <pre>
     * Data Smoothing
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
     * 9;</code>
     *
     * @param value The smoothingOption to set.
     * @return This builder for chaining.
     */
    public Builder setSmoothingOption(SmoothingOptions value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      smoothingOption_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Data Smoothing
     * </pre>
     *
     * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
     * 9;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSmoothingOption() {
      bitField0_ = (bitField0_ & ~0x00000100);
      smoothingOption_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest)
  private static final GetSpectraRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetSpectraRequest();
  }

  public static GetSpectraRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSpectraRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetSpectraRequest>() {
    @Override
    public GetSpectraRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSpectraRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetSpectraRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public GetSpectraRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

