/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface GetScanXicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.GetScanXicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the id of the sample 
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The sampleId.
   */
  String getSampleId();
  /**
   * <pre>
   * the id of the sample 
   * </pre>
   *
   * <code>string SampleId = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * &#47; the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The experimentId.
   */
  String getExperimentId();
  /**
   * <pre>
   * &#47; the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 2;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();

  /**
   * <pre>
   * &#47; the list of mass ranges
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MassRange MassRanges = 3;</code>
   */
  java.util.List<MassRange>
      getMassRangesList();
  /**
   * <pre>
   * &#47; the list of mass ranges
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MassRange MassRanges = 3;</code>
   */
  MassRange getMassRanges(int index);
  /**
   * <pre>
   * &#47; the list of mass ranges
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MassRange MassRanges = 3;</code>
   */
  int getMassRangesCount();
  /**
   * <pre>
   * &#47; the list of mass ranges
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MassRange MassRanges = 3;</code>
   */
  java.util.List<? extends MassRangeOrBuilder>
      getMassRangesOrBuilderList();
  /**
   * <pre>
   * &#47; the list of mass ranges
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MassRange MassRanges = 3;</code>
   */
  MassRangeOrBuilder getMassRangesOrBuilder(
      int index);

  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   * @return Whether the cycleRange field is set.
   */
  boolean hasCycleRange();
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   * @return The cycleRange.
   */
  CycleRange getCycleRange();
  /**
   * <pre>
   * &#47; the range of cycles
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.CycleRange CycleRange = 4;</code>
   */
  CycleRangeOrBuilder getCycleRangeOrBuilder();

  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   * @return Whether the timeRange field is set.
   */
  boolean hasTimeRange();
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   * @return The timeRange.
   */
  TimeRange getTimeRange();
  /**
   * <pre>
   * &#47; the range of the time
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange TimeRange = 5;</code>
   */
  TimeRangeOrBuilder getTimeRangeOrBuilder();
}
