/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

@com.google.protobuf.Generated
public interface GetSpectraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Clearcore2.SampleData.DataAccessApi.V002.GetSpectraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This is a time window for sub selecting a subset of information 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <pre>
   * This is a time window for sub selecting a subset of information 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   * @return The range.
   */
  TimeRange getRange();
  /**
   * <pre>
   * This is a time window for sub selecting a subset of information 
   * </pre>
   *
   * <code>.Clearcore2.SampleData.DataAccessApi.V002.TimeRange Range = 1;</code>
   */
  TimeRangeOrBuilder getRangeOrBuilder();

  /**
   * <pre>
   * the id of the sample
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The sampleId.
   */
  String getSampleId();
  /**
   * <pre>
   * the id of the sample
   * </pre>
   *
   * <code>string SampleId = 2;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 3;</code>
   * @return The experimentId.
   */
  String getExperimentId();
  /**
   * <pre>
   * the id of the experiment
   * </pre>
   *
   * <code>string ExperimentId = 3;</code>
   * @return The bytes for experimentId.
   */
  com.google.protobuf.ByteString
      getExperimentIdBytes();

  /**
   * <pre>
   * if true then the data is returned in the Centroid format (i.e. it will be processed using spectral peaks finder)
   * </pre>
   *
   * <code>bool ConvertToCentroid = 4;</code>
   * @return The convertToCentroid.
   */
  boolean getConvertToCentroid();

  /**
   * <pre>
   * if the value is greater than 0 process the data to add framing zeros 
   * (data will be processed - this operation incurs overhead)
   * default 1
   * </pre>
   *
   * <code>int32 AddFramingZeros = 5;</code>
   * @return The addFramingZeros.
   */
  int getAddFramingZeros();

  /**
   * <pre>
   * This flag when set to false will set the framing zeros to one
   * </pre>
   *
   * <code>bool OverrideAddFramingZerosDefaultValue = 6;</code>
   * @return The overrideAddFramingZerosDefaultValue.
   */
  boolean getOverrideAddFramingZerosDefaultValue();

  /**
   * <pre>
   * This metric specifies which peak metric should be returned as the y-values when centroiding.
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
   * @return Whether the centroidOption field is set.
   */
  boolean hasCentroidOption();
  /**
   * <pre>
   * This metric specifies which peak metric should be returned as the y-values when centroiding.
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
   * @return The enum numeric value on the wire for centroidOption.
   */
  int getCentroidOptionValue();
  /**
   * <pre>
   * This metric specifies which peak metric should be returned as the y-values when centroiding.
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.CentroidOptions CentroidOption = 7;</code>
   * @return The centroidOption.
   */
  CentroidOptions getCentroidOption();

  /**
   * <pre>
   * Indicates whether to include isolated points as peaks.
   * </pre>
   *
   * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
   *
   * @return Whether the includeIsolatedPointsAsPeaks field is set.
   */
  boolean hasIncludeIsolatedPointsAsPeaks();

  /**
   * <pre>
   * Indicates whether to include isolated points as peaks.
   * </pre>
   *
   * <code>optional bool IncludeIsolatedPointsAsPeaks = 8;</code>
   *
   * @return The includeIsolatedPointsAsPeaks.
   */
  boolean getIncludeIsolatedPointsAsPeaks();

  /**
   * <pre>
   * Data Smoothing
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
   * 9;</code>
   *
   * @return Whether the smoothingOption field is set.
   */
  boolean hasSmoothingOption();

  /**
   * <pre>
   * Data Smoothing
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
   * 9;</code>
   *
   * @return The enum numeric value on the wire for smoothingOption.
   */
  int getSmoothingOptionValue();

  /**
   * <pre>
   * Data Smoothing
   * </pre>
   *
   * <code>optional .Clearcore2.SampleData.DataAccessApi.V002.SmoothingOptions SmoothingOption =
   * 9;</code>
   *
   * @return The smoothingOption.
   */
  SmoothingOptions getSmoothingOption();
}
