/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * Instrument information.
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.InstrumentDetail}
 */
@com.google.protobuf.Generated
public final class InstrumentDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.InstrumentDetail)
    InstrumentDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "InstrumentDetail");
  }
  // Use InstrumentDetail.newBuilder() to construct.
  private InstrumentDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InstrumentDetail() {
    deviceModelName_ = "";
    serialNumber_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_InstrumentDetail_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_InstrumentDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InstrumentDetail.class, Builder.class);
  }

  public static final int DEVICETYPE_FIELD_NUMBER = 1;
  private int deviceType_ = 0;
  /**
   * <pre>
   * Returns the type of instrument 
   * MassSpectrometer = 0
   * Autosampler = 1
   * ColumnOven = 2
   * ADConverter = 3
   * Valve = 4
   * SyringePump = 5
   * IntegratedSystem = 6
   * Detector = 7
   * LCPump = 8  
   * </pre>
   *
   * <code>int32 DeviceType = 1;</code>
   * @return The deviceType.
   */
  @Override
  public int getDeviceType() {
    return deviceType_;
  }

  public static final int DEVICEMODELNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object deviceModelName_ = "";
  /**
   * <pre>
   * Returns the instrument device model name.
   * </pre>
   *
   * <code>string DeviceModelName = 2;</code>
   * @return The deviceModelName.
   */
  @Override
  public String getDeviceModelName() {
    Object ref = deviceModelName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceModelName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Returns the instrument device model name.
   * </pre>
   *
   * <code>string DeviceModelName = 2;</code>
   * @return The bytes for deviceModelName.
   */
  @Override
  public com.google.protobuf.ByteString
      getDeviceModelNameBytes() {
    Object ref = deviceModelName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceModelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERIALNUMBER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object serialNumber_ = "";
  /**
   * <pre>
   * Gets the instrument serial number. 
   * </pre>
   *
   * <code>string SerialNumber = 3;</code>
   * @return The serialNumber.
   */
  @Override
  public String getSerialNumber() {
    Object ref = serialNumber_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serialNumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Gets the instrument serial number. 
   * </pre>
   *
   * <code>string SerialNumber = 3;</code>
   * @return The bytes for serialNumber.
   */
  @Override
  public com.google.protobuf.ByteString
      getSerialNumberBytes() {
    Object ref = serialNumber_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serialNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (deviceType_ != 0) {
      output.writeInt32(1, deviceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceModelName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, deviceModelName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serialNumber_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, serialNumber_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (deviceType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, deviceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceModelName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deviceModelName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serialNumber_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, serialNumber_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InstrumentDetail)) {
      return super.equals(obj);
    }
    InstrumentDetail other = (InstrumentDetail) obj;

    if (getDeviceType()
        != other.getDeviceType()) return false;
    if (!getDeviceModelName()
        .equals(other.getDeviceModelName())) return false;
    if (!getSerialNumber()
        .equals(other.getSerialNumber())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceType();
    hash = (37 * hash) + DEVICEMODELNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceModelName().hashCode();
    hash = (37 * hash) + SERIALNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSerialNumber().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InstrumentDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InstrumentDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InstrumentDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InstrumentDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InstrumentDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InstrumentDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InstrumentDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static InstrumentDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static InstrumentDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static InstrumentDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InstrumentDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static InstrumentDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InstrumentDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Instrument information.
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.InstrumentDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.InstrumentDetail)
      InstrumentDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_InstrumentDetail_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_InstrumentDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InstrumentDetail.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.InstrumentDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      deviceType_ = 0;
      deviceModelName_ = "";
      serialNumber_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_InstrumentDetail_descriptor;
    }

    @Override
    public InstrumentDetail getDefaultInstanceForType() {
      return InstrumentDetail.getDefaultInstance();
    }

    @Override
    public InstrumentDetail build() {
      InstrumentDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public InstrumentDetail buildPartial() {
      InstrumentDetail result = new InstrumentDetail(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(InstrumentDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.deviceType_ = deviceType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.deviceModelName_ = deviceModelName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.serialNumber_ = serialNumber_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InstrumentDetail) {
        return mergeFrom((InstrumentDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InstrumentDetail other) {
      if (other == InstrumentDetail.getDefaultInstance()) return this;
      if (other.getDeviceType() != 0) {
        setDeviceType(other.getDeviceType());
      }
      if (!other.getDeviceModelName().isEmpty()) {
        deviceModelName_ = other.deviceModelName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSerialNumber().isEmpty()) {
        serialNumber_ = other.serialNumber_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              deviceType_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              deviceModelName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              serialNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int deviceType_ ;
    /**
     * <pre>
     * Returns the type of instrument 
     * MassSpectrometer = 0
     * Autosampler = 1
     * ColumnOven = 2
     * ADConverter = 3
     * Valve = 4
     * SyringePump = 5
     * IntegratedSystem = 6
     * Detector = 7
     * LCPump = 8  
     * </pre>
     *
     * <code>int32 DeviceType = 1;</code>
     * @return The deviceType.
     */
    @Override
    public int getDeviceType() {
      return deviceType_;
    }
    /**
     * <pre>
     * Returns the type of instrument 
     * MassSpectrometer = 0
     * Autosampler = 1
     * ColumnOven = 2
     * ADConverter = 3
     * Valve = 4
     * SyringePump = 5
     * IntegratedSystem = 6
     * Detector = 7
     * LCPump = 8  
     * </pre>
     *
     * <code>int32 DeviceType = 1;</code>
     * @param value The deviceType to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceType(int value) {

      deviceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Returns the type of instrument 
     * MassSpectrometer = 0
     * Autosampler = 1
     * ColumnOven = 2
     * ADConverter = 3
     * Valve = 4
     * SyringePump = 5
     * IntegratedSystem = 6
     * Detector = 7
     * LCPump = 8  
     * </pre>
     *
     * <code>int32 DeviceType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      deviceType_ = 0;
      onChanged();
      return this;
    }

    private Object deviceModelName_ = "";
    /**
     * <pre>
     * Returns the instrument device model name.
     * </pre>
     *
     * <code>string DeviceModelName = 2;</code>
     * @return The deviceModelName.
     */
    public String getDeviceModelName() {
      Object ref = deviceModelName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceModelName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Returns the instrument device model name.
     * </pre>
     *
     * <code>string DeviceModelName = 2;</code>
     * @return The bytes for deviceModelName.
     */
    public com.google.protobuf.ByteString
        getDeviceModelNameBytes() {
      Object ref = deviceModelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceModelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Returns the instrument device model name.
     * </pre>
     *
     * <code>string DeviceModelName = 2;</code>
     * @param value The deviceModelName to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModelName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceModelName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Returns the instrument device model name.
     * </pre>
     *
     * <code>string DeviceModelName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceModelName() {
      deviceModelName_ = getDefaultInstance().getDeviceModelName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Returns the instrument device model name.
     * </pre>
     *
     * <code>string DeviceModelName = 2;</code>
     * @param value The bytes for deviceModelName to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceModelName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object serialNumber_ = "";
    /**
     * <pre>
     * Gets the instrument serial number. 
     * </pre>
     *
     * <code>string SerialNumber = 3;</code>
     * @return The serialNumber.
     */
    public String getSerialNumber() {
      Object ref = serialNumber_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serialNumber_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Gets the instrument serial number. 
     * </pre>
     *
     * <code>string SerialNumber = 3;</code>
     * @return The bytes for serialNumber.
     */
    public com.google.protobuf.ByteString
        getSerialNumberBytes() {
      Object ref = serialNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serialNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Gets the instrument serial number. 
     * </pre>
     *
     * <code>string SerialNumber = 3;</code>
     * @param value The serialNumber to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNumber(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      serialNumber_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gets the instrument serial number. 
     * </pre>
     *
     * <code>string SerialNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerialNumber() {
      serialNumber_ = getDefaultInstance().getSerialNumber();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gets the instrument serial number. 
     * </pre>
     *
     * <code>string SerialNumber = 3;</code>
     * @param value The bytes for serialNumber to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serialNumber_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.InstrumentDetail)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.InstrumentDetail)
  private static final InstrumentDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InstrumentDetail();
  }

  public static InstrumentDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstrumentDetail>
      PARSER = new com.google.protobuf.AbstractParser<InstrumentDetail>() {
    @Override
    public InstrumentDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InstrumentDetail> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<InstrumentDetail> getParserForType() {
    return PARSER;
  }

  @Override
  public InstrumentDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

