/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * MsMethod Experiment information.
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment}
 */
@com.google.protobuf.Generated
public final class MsMethodExperiment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment)
    MsMethodExperimentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "MsMethodExperiment");
  }
  // Use MsMethodExperiment.newBuilder() to construct.
  private MsMethodExperiment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MsMethodExperiment() {
    name_ = "";
    parameters_ = java.util.Collections.emptyList();
    experiments_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethodExperiment_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethodExperiment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MsMethodExperiment.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object name_ = "";
  /**
   * <pre>
   * returns name of the parameter
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * returns name of the parameter
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_ = 0;

  /**
   * <pre>
   * returns the id of the experiment
   * </pre>
   *
   * <code>int32 Id = 2;</code>
   *
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int PARAMETERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<Parameter> parameters_;
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
   */
  @Override
  public java.util.List<Parameter> getParametersList() {
    return parameters_;
  }
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
   */
  @Override
  public java.util.List<? extends ParameterOrBuilder>
      getParametersOrBuilderList() {
    return parameters_;
  }
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
   */
  @Override
  public int getParametersCount() {
    return parameters_.size();
  }
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
   */
  @Override
  public Parameter getParameters(int index) {
    return parameters_.get(index);
  }
  /**
   * <pre>
   * returns the parameters for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
   */
  @Override
  public ParameterOrBuilder getParametersOrBuilder(
      int index) {
    return parameters_.get(index);
  }

  public static final int EXPERIMENTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<MsMethodExperiment> experiments_;
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
   */
  @Override
  public java.util.List<MsMethodExperiment> getExperimentsList() {
    return experiments_;
  }
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
   */
  @Override
  public java.util.List<? extends MsMethodExperimentOrBuilder>
      getExperimentsOrBuilderList() {
    return experiments_;
  }
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
   */
  @Override
  public int getExperimentsCount() {
    return experiments_.size();
  }
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
   */
  @Override
  public MsMethodExperiment getExperiments(int index) {
    return experiments_.get(index);
  }
  /**
   * <pre>
   * returns the sub experiments for this experiment
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
   */
  @Override
  public MsMethodExperimentOrBuilder getExperimentsOrBuilder(
      int index) {
    return experiments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    for (int i = 0; i < parameters_.size(); i++) {
      output.writeMessage(3, parameters_.get(i));
    }
    for (int i = 0; i < experiments_.size(); i++) {
      output.writeMessage(4, experiments_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, id_);
    }
    for (int i = 0; i < parameters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, parameters_.get(i));
    }
    for (int i = 0; i < experiments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, experiments_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MsMethodExperiment)) {
      return super.equals(obj);
    }
    MsMethodExperiment other = (MsMethodExperiment) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getId() != other.getId()) {
      return false;
    }
    if (!getParametersList()
        .equals(other.getParametersList())) return false;
    if (!getExperimentsList()
        .equals(other.getExperimentsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (getParametersCount() > 0) {
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParametersList().hashCode();
    }
    if (getExperimentsCount() > 0) {
      hash = (37 * hash) + EXPERIMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getExperimentsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MsMethodExperiment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MsMethodExperiment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MsMethodExperiment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MsMethodExperiment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MsMethodExperiment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MsMethodExperiment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MsMethodExperiment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static MsMethodExperiment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static MsMethodExperiment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static MsMethodExperiment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MsMethodExperiment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static MsMethodExperiment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MsMethodExperiment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MsMethod Experiment information.
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment)
      MsMethodExperimentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethodExperiment_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethodExperiment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsMethodExperiment.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.MsMethodExperiment.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      id_ = 0;
      if (parametersBuilder_ == null) {
        parameters_ = java.util.Collections.emptyList();
      } else {
        parameters_ = null;
        parametersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (experimentsBuilder_ == null) {
        experiments_ = java.util.Collections.emptyList();
      } else {
        experiments_ = null;
        experimentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_MsMethodExperiment_descriptor;
    }

    @Override
    public MsMethodExperiment getDefaultInstanceForType() {
      return MsMethodExperiment.getDefaultInstance();
    }

    @Override
    public MsMethodExperiment build() {
      MsMethodExperiment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MsMethodExperiment buildPartial() {
      MsMethodExperiment result = new MsMethodExperiment(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(MsMethodExperiment result) {
      if (parametersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          parameters_ = java.util.Collections.unmodifiableList(parameters_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parameters_ = parameters_;
      } else {
        result.parameters_ = parametersBuilder_.build();
      }
      if (experimentsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          experiments_ = java.util.Collections.unmodifiableList(experiments_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.experiments_ = experiments_;
      } else {
        result.experiments_ = experimentsBuilder_.build();
      }
    }

    private void buildPartial0(MsMethodExperiment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = id_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MsMethodExperiment) {
        return mergeFrom((MsMethodExperiment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MsMethodExperiment other) {
      if (other == MsMethodExperiment.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (parametersBuilder_ == null) {
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
      } else {
        if (!other.parameters_.isEmpty()) {
          if (parametersBuilder_.isEmpty()) {
            parametersBuilder_.dispose();
            parametersBuilder_ = null;
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000004);
            parametersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetParametersFieldBuilder() : null;
          } else {
            parametersBuilder_.addAllMessages(other.parameters_);
          }
        }
      }
      if (experimentsBuilder_ == null) {
        if (!other.experiments_.isEmpty()) {
          if (experiments_.isEmpty()) {
            experiments_ = other.experiments_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureExperimentsIsMutable();
            experiments_.addAll(other.experiments_);
          }
          onChanged();
        }
      } else {
        if (!other.experiments_.isEmpty()) {
          if (experimentsBuilder_.isEmpty()) {
            experimentsBuilder_.dispose();
            experimentsBuilder_ = null;
            experiments_ = other.experiments_;
            bitField0_ = (bitField0_ & ~0x00000008);
            experimentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetExperimentsFieldBuilder() : null;
          } else {
            experimentsBuilder_.addAllMessages(other.experiments_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              Parameter m =
                  input.readMessage(
                      Parameter.parser(),
                      extensionRegistry);
              if (parametersBuilder_ == null) {
                ensureParametersIsMutable();
                parameters_.add(m);
              } else {
                parametersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              MsMethodExperiment m =
                  input.readMessage(
                      MsMethodExperiment.parser(),
                      extensionRegistry);
              if (experimentsBuilder_ == null) {
                ensureExperimentsIsMutable();
                experiments_.add(m);
              } else {
                experimentsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <pre>
     * returns name of the parameter
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * returns name of the parameter
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * returns name of the parameter
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * returns name of the parameter
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * returns name of the parameter
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int id_;

    /**
     * <pre>
     * returns the id of the experiment
     * </pre>
     *
     * <code>int32 Id = 2;</code>
     *
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    /**
     * <pre>
     * returns the id of the experiment
     * </pre>
     *
     * <code>int32 Id = 2;</code>
     *
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * returns the id of the experiment
     * </pre>
     *
     * <code>int32 Id = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<Parameter> parameters_ =
      java.util.Collections.emptyList();
    private void ensureParametersIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        parameters_ = new java.util.ArrayList<Parameter>(parameters_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Parameter, Parameter.Builder, ParameterOrBuilder> parametersBuilder_;

    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public java.util.List<Parameter> getParametersList() {
      if (parametersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parameters_);
      } else {
        return parametersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public int getParametersCount() {
      if (parametersBuilder_ == null) {
        return parameters_.size();
      } else {
        return parametersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Parameter getParameters(int index) {
      if (parametersBuilder_ == null) {
        return parameters_.get(index);
      } else {
        return parametersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder setParameters(
        int index, Parameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
      } else {
        parametersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder setParameters(
        int index, Parameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.set(index, builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder addParameters(Parameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
      } else {
        parametersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder addParameters(
        int index, Parameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.add(index, value);
        onChanged();
      } else {
        parametersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder addParameters(
        Parameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.add(builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder addParameters(
        int index, Parameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.add(index, builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder addAllParameters(
        Iterable<? extends Parameter> values) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        onChanged();
      } else {
        parametersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder clearParameters() {
      if (parametersBuilder_ == null) {
        parameters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        parametersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Builder removeParameters(int index) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.remove(index);
        onChanged();
      } else {
        parametersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Parameter.Builder getParametersBuilder(
        int index) {
      return internalGetParametersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public ParameterOrBuilder getParametersOrBuilder(
        int index) {
      if (parametersBuilder_ == null) {
        return parameters_.get(index);  } else {
        return parametersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public java.util.List<? extends ParameterOrBuilder>
         getParametersOrBuilderList() {
      if (parametersBuilder_ != null) {
        return parametersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parameters_);
      }
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Parameter.Builder addParametersBuilder() {
      return internalGetParametersFieldBuilder().addBuilder(
          Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public Parameter.Builder addParametersBuilder(
        int index) {
      return internalGetParametersFieldBuilder().addBuilder(
          index, Parameter.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the parameters for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Parameter Parameters = 3;</code>
     */
    public java.util.List<Parameter.Builder>
         getParametersBuilderList() {
      return internalGetParametersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Parameter, Parameter.Builder, ParameterOrBuilder>
        internalGetParametersFieldBuilder() {
      if (parametersBuilder_ == null) {
        parametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Parameter, Parameter.Builder, ParameterOrBuilder>(parameters_,
            ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        parameters_ = null;
      }
      return parametersBuilder_;
    }

    private java.util.List<MsMethodExperiment> experiments_ =
      java.util.Collections.emptyList();
    private void ensureExperimentsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        experiments_ = new java.util.ArrayList<MsMethodExperiment>(experiments_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        MsMethodExperiment, Builder, MsMethodExperimentOrBuilder> experimentsBuilder_;

    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public java.util.List<MsMethodExperiment> getExperimentsList() {
      if (experimentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(experiments_);
      } else {
        return experimentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public int getExperimentsCount() {
      if (experimentsBuilder_ == null) {
        return experiments_.size();
      } else {
        return experimentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public MsMethodExperiment getExperiments(int index) {
      if (experimentsBuilder_ == null) {
        return experiments_.get(index);
      } else {
        return experimentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder setExperiments(
        int index, MsMethodExperiment value) {
      if (experimentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExperimentsIsMutable();
        experiments_.set(index, value);
        onChanged();
      } else {
        experimentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder setExperiments(
        int index, Builder builderForValue) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.set(index, builderForValue.build());
        onChanged();
      } else {
        experimentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addExperiments(MsMethodExperiment value) {
      if (experimentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExperimentsIsMutable();
        experiments_.add(value);
        onChanged();
      } else {
        experimentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addExperiments(
        int index, MsMethodExperiment value) {
      if (experimentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExperimentsIsMutable();
        experiments_.add(index, value);
        onChanged();
      } else {
        experimentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addExperiments(
        Builder builderForValue) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.add(builderForValue.build());
        onChanged();
      } else {
        experimentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addExperiments(
        int index, Builder builderForValue) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.add(index, builderForValue.build());
        onChanged();
      } else {
        experimentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addAllExperiments(
        Iterable<? extends MsMethodExperiment> values) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, experiments_);
        onChanged();
      } else {
        experimentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder clearExperiments() {
      if (experimentsBuilder_ == null) {
        experiments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        experimentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder removeExperiments(int index) {
      if (experimentsBuilder_ == null) {
        ensureExperimentsIsMutable();
        experiments_.remove(index);
        onChanged();
      } else {
        experimentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder getExperimentsBuilder(
        int index) {
      return internalGetExperimentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public MsMethodExperimentOrBuilder getExperimentsOrBuilder(
        int index) {
      if (experimentsBuilder_ == null) {
        return experiments_.get(index);  } else {
        return experimentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public java.util.List<? extends MsMethodExperimentOrBuilder>
         getExperimentsOrBuilderList() {
      if (experimentsBuilder_ != null) {
        return experimentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(experiments_);
      }
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addExperimentsBuilder() {
      return internalGetExperimentsFieldBuilder().addBuilder(
          MsMethodExperiment.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public Builder addExperimentsBuilder(
        int index) {
      return internalGetExperimentsFieldBuilder().addBuilder(
          index, MsMethodExperiment.getDefaultInstance());
    }
    /**
     * <pre>
     * returns the sub experiments for this experiment
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment Experiments = 4;</code>
     */
    public java.util.List<Builder>
         getExperimentsBuilderList() {
      return internalGetExperimentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        MsMethodExperiment, Builder, MsMethodExperimentOrBuilder>
        internalGetExperimentsFieldBuilder() {
      if (experimentsBuilder_ == null) {
        experimentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            MsMethodExperiment, Builder, MsMethodExperimentOrBuilder>(experiments_,
            ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        experiments_ = null;
      }
      return experimentsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.MsMethodExperiment)
  private static final MsMethodExperiment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MsMethodExperiment();
  }

  public static MsMethodExperiment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsMethodExperiment>
      PARSER = new com.google.protobuf.AbstractParser<MsMethodExperiment>() {
    @Override
    public MsMethodExperiment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MsMethodExperiment> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MsMethodExperiment> getParserForType() {
    return PARSER;
  }

  @Override
  public MsMethodExperiment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

