/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * Enum to hold the type.
 * </pre>
 *
 * Protobuf enum {@code Clearcore2.SampleData.DataAccessApi.V002.ParameterType}
 */
@com.google.protobuf.Generated
public enum ParameterType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * field type unknown.
   * </pre>
   *
   * <code>Unknown = 0;</code>
   */
  Unknown(0),
  /**
   * <pre>
   * field type double.
   * </pre>
   *
   * <code>Double = 1;</code>
   */
  Double(1),
  /**
   * <pre>
   * field type integer.
   * </pre>
   *
   * <code>Int32 = 2;</code>
   */
  Int32(2),
  /**
   * <pre>
   * field type bool.
   * </pre>
   *
   * <code>Boolean = 3;</code>
   */
  Boolean(3),
  /**
   * <pre>
   * field type string.
   * </pre>
   *
   * <code>String = 4;</code>
   */
  String(4),
  /**
   * <pre>
   * field type datetime.
   * </pre>
   *
   * <code>DateTime = 5;</code>
   */
  DateTime(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ParameterType");
  }
  /**
   * <pre>
   * field type unknown.
   * </pre>
   *
   * <code>Unknown = 0;</code>
   */
  public static final int Unknown_VALUE = 0;
  /**
   * <pre>
   * field type double.
   * </pre>
   *
   * <code>Double = 1;</code>
   */
  public static final int Double_VALUE = 1;
  /**
   * <pre>
   * field type integer.
   * </pre>
   *
   * <code>Int32 = 2;</code>
   */
  public static final int Int32_VALUE = 2;
  /**
   * <pre>
   * field type bool.
   * </pre>
   *
   * <code>Boolean = 3;</code>
   */
  public static final int Boolean_VALUE = 3;
  /**
   * <pre>
   * field type string.
   * </pre>
   *
   * <code>String = 4;</code>
   */
  public static final int String_VALUE = 4;
  /**
   * <pre>
   * field type datetime.
   * </pre>
   *
   * <code>DateTime = 5;</code>
   */
  public static final int DateTime_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ParameterType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ParameterType forNumber(int value) {
    switch (value) {
      case 0: return Unknown;
      case 1: return Double;
      case 2: return Int32;
      case 3: return Boolean;
      case 4: return String;
      case 5: return DateTime;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ParameterType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ParameterType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ParameterType>() {
          public ParameterType findValueByNumber(int number) {
            return ParameterType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.getDescriptor().getEnumTypes().get(2);
  }

  private static final ParameterType[] VALUES = values();

  public static ParameterType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ParameterType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Clearcore2.SampleData.DataAccessApi.V002.ParameterType)
}

