/*
 * Copyright (c) 2004-2026 The mzmine Development Team
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Clearcore2.SampleData.Grpc.Contracts.proto
// Protobuf Java Version: 4.33.0

package io.github.mzmine.modules.io.import_rawdata_wiff2.api;

/**
 * <pre>
 * Gets the sections for the sample information.
 * </pre>
 *
 * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.SampleInfoSection}
 */
@com.google.protobuf.Generated
public final class SampleInfoSection extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Clearcore2.SampleData.DataAccessApi.V002.SampleInfoSection)
    SampleInfoSectionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "SampleInfoSection");
  }
  // Use SampleInfoSection.newBuilder() to construct.
  private SampleInfoSection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SampleInfoSection() {
    name_ = "";
    paragraphs_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_SampleInfoSection_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_SampleInfoSection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SampleInfoSection.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object name_ = "";
  /**
   * <pre>
   * Section name.
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Section name.
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAGRAPHS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<Paragraph> paragraphs_;
  /**
   * <pre>
   * Get the paragraphs.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
   */
  @Override
  public java.util.List<Paragraph> getParagraphsList() {
    return paragraphs_;
  }
  /**
   * <pre>
   * Get the paragraphs.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
   */
  @Override
  public java.util.List<? extends ParagraphOrBuilder>
      getParagraphsOrBuilderList() {
    return paragraphs_;
  }
  /**
   * <pre>
   * Get the paragraphs.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
   */
  @Override
  public int getParagraphsCount() {
    return paragraphs_.size();
  }
  /**
   * <pre>
   * Get the paragraphs.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
   */
  @Override
  public Paragraph getParagraphs(int index) {
    return paragraphs_.get(index);
  }
  /**
   * <pre>
   * Get the paragraphs.
   * </pre>
   *
   * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
   */
  @Override
  public ParagraphOrBuilder getParagraphsOrBuilder(
      int index) {
    return paragraphs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    for (int i = 0; i < paragraphs_.size(); i++) {
      output.writeMessage(2, paragraphs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    for (int i = 0; i < paragraphs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, paragraphs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SampleInfoSection)) {
      return super.equals(obj);
    }
    SampleInfoSection other = (SampleInfoSection) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getParagraphsList()
        .equals(other.getParagraphsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getParagraphsCount() > 0) {
      hash = (37 * hash) + PARAGRAPHS_FIELD_NUMBER;
      hash = (53 * hash) + getParagraphsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SampleInfoSection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SampleInfoSection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SampleInfoSection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SampleInfoSection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SampleInfoSection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SampleInfoSection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SampleInfoSection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static SampleInfoSection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static SampleInfoSection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static SampleInfoSection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SampleInfoSection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static SampleInfoSection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SampleInfoSection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Gets the sections for the sample information.
   * </pre>
   *
   * Protobuf type {@code Clearcore2.SampleData.DataAccessApi.V002.SampleInfoSection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Clearcore2.SampleData.DataAccessApi.V002.SampleInfoSection)
      SampleInfoSectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_SampleInfoSection_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_SampleInfoSection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SampleInfoSection.class, Builder.class);
    }

    // Construct using io.github.mzmine.modules.io.import_rawdata_wiff2.api.SampleInfoSection.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      if (paragraphsBuilder_ == null) {
        paragraphs_ = java.util.Collections.emptyList();
      } else {
        paragraphs_ = null;
        paragraphsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Clearcore2SampleDataGrpcContracts.internal_static_Clearcore2_SampleData_DataAccessApi_V002_SampleInfoSection_descriptor;
    }

    @Override
    public SampleInfoSection getDefaultInstanceForType() {
      return SampleInfoSection.getDefaultInstance();
    }

    @Override
    public SampleInfoSection build() {
      SampleInfoSection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SampleInfoSection buildPartial() {
      SampleInfoSection result = new SampleInfoSection(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(SampleInfoSection result) {
      if (paragraphsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          paragraphs_ = java.util.Collections.unmodifiableList(paragraphs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.paragraphs_ = paragraphs_;
      } else {
        result.paragraphs_ = paragraphsBuilder_.build();
      }
    }

    private void buildPartial0(SampleInfoSection result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SampleInfoSection) {
        return mergeFrom((SampleInfoSection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SampleInfoSection other) {
      if (other == SampleInfoSection.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (paragraphsBuilder_ == null) {
        if (!other.paragraphs_.isEmpty()) {
          if (paragraphs_.isEmpty()) {
            paragraphs_ = other.paragraphs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParagraphsIsMutable();
            paragraphs_.addAll(other.paragraphs_);
          }
          onChanged();
        }
      } else {
        if (!other.paragraphs_.isEmpty()) {
          if (paragraphsBuilder_.isEmpty()) {
            paragraphsBuilder_.dispose();
            paragraphsBuilder_ = null;
            paragraphs_ = other.paragraphs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            paragraphsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetParagraphsFieldBuilder() : null;
          } else {
            paragraphsBuilder_.addAllMessages(other.paragraphs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              Paragraph m =
                  input.readMessage(
                      Paragraph.parser(),
                      extensionRegistry);
              if (paragraphsBuilder_ == null) {
                ensureParagraphsIsMutable();
                paragraphs_.add(m);
              } else {
                paragraphsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <pre>
     * Section name.
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Section name.
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Section name.
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Section name.
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Section name.
     * </pre>
     *
     * <code>string Name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<Paragraph> paragraphs_ =
      java.util.Collections.emptyList();
    private void ensureParagraphsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        paragraphs_ = new java.util.ArrayList<Paragraph>(paragraphs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        Paragraph, Paragraph.Builder, ParagraphOrBuilder> paragraphsBuilder_;

    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public java.util.List<Paragraph> getParagraphsList() {
      if (paragraphsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(paragraphs_);
      } else {
        return paragraphsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public int getParagraphsCount() {
      if (paragraphsBuilder_ == null) {
        return paragraphs_.size();
      } else {
        return paragraphsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Paragraph getParagraphs(int index) {
      if (paragraphsBuilder_ == null) {
        return paragraphs_.get(index);
      } else {
        return paragraphsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder setParagraphs(
        int index, Paragraph value) {
      if (paragraphsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParagraphsIsMutable();
        paragraphs_.set(index, value);
        onChanged();
      } else {
        paragraphsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder setParagraphs(
        int index, Paragraph.Builder builderForValue) {
      if (paragraphsBuilder_ == null) {
        ensureParagraphsIsMutable();
        paragraphs_.set(index, builderForValue.build());
        onChanged();
      } else {
        paragraphsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder addParagraphs(Paragraph value) {
      if (paragraphsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParagraphsIsMutable();
        paragraphs_.add(value);
        onChanged();
      } else {
        paragraphsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder addParagraphs(
        int index, Paragraph value) {
      if (paragraphsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParagraphsIsMutable();
        paragraphs_.add(index, value);
        onChanged();
      } else {
        paragraphsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder addParagraphs(
        Paragraph.Builder builderForValue) {
      if (paragraphsBuilder_ == null) {
        ensureParagraphsIsMutable();
        paragraphs_.add(builderForValue.build());
        onChanged();
      } else {
        paragraphsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder addParagraphs(
        int index, Paragraph.Builder builderForValue) {
      if (paragraphsBuilder_ == null) {
        ensureParagraphsIsMutable();
        paragraphs_.add(index, builderForValue.build());
        onChanged();
      } else {
        paragraphsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder addAllParagraphs(
        Iterable<? extends Paragraph> values) {
      if (paragraphsBuilder_ == null) {
        ensureParagraphsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paragraphs_);
        onChanged();
      } else {
        paragraphsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder clearParagraphs() {
      if (paragraphsBuilder_ == null) {
        paragraphs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        paragraphsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Builder removeParagraphs(int index) {
      if (paragraphsBuilder_ == null) {
        ensureParagraphsIsMutable();
        paragraphs_.remove(index);
        onChanged();
      } else {
        paragraphsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Paragraph.Builder getParagraphsBuilder(
        int index) {
      return internalGetParagraphsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public ParagraphOrBuilder getParagraphsOrBuilder(
        int index) {
      if (paragraphsBuilder_ == null) {
        return paragraphs_.get(index);  } else {
        return paragraphsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public java.util.List<? extends ParagraphOrBuilder>
         getParagraphsOrBuilderList() {
      if (paragraphsBuilder_ != null) {
        return paragraphsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(paragraphs_);
      }
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Paragraph.Builder addParagraphsBuilder() {
      return internalGetParagraphsFieldBuilder().addBuilder(
          Paragraph.getDefaultInstance());
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public Paragraph.Builder addParagraphsBuilder(
        int index) {
      return internalGetParagraphsFieldBuilder().addBuilder(
          index, Paragraph.getDefaultInstance());
    }
    /**
     * <pre>
     * Get the paragraphs.
     * </pre>
     *
     * <code>repeated .Clearcore2.SampleData.DataAccessApi.V002.Paragraph Paragraphs = 2;</code>
     */
    public java.util.List<Paragraph.Builder>
         getParagraphsBuilderList() {
      return internalGetParagraphsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        Paragraph, Paragraph.Builder, ParagraphOrBuilder>
        internalGetParagraphsFieldBuilder() {
      if (paragraphsBuilder_ == null) {
        paragraphsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            Paragraph, Paragraph.Builder, ParagraphOrBuilder>(
                paragraphs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        paragraphs_ = null;
      }
      return paragraphsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Clearcore2.SampleData.DataAccessApi.V002.SampleInfoSection)
  }

  // @@protoc_insertion_point(class_scope:Clearcore2.SampleData.DataAccessApi.V002.SampleInfoSection)
  private static final SampleInfoSection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SampleInfoSection();
  }

  public static SampleInfoSection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SampleInfoSection>
      PARSER = new com.google.protobuf.AbstractParser<SampleInfoSection>() {
    @Override
    public SampleInfoSection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SampleInfoSection> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SampleInfoSection> getParserForType() {
    return PARSER;
  }

  @Override
  public SampleInfoSection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

