{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "memory-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 4945,
          "sha512": "9832efa5a84dbb8929305f889f4905b64295b5586be93d5944d16c2fba3a7947dae1d3f79c02ed6bd66d819724cb0804f3fcfc2f9c4929973ac208979a1c58e8",
          "sha256": "6a929a90e52694bb82071a6028891d7509b48094acc06cada1b7a84af9c96964",
          "sha1": "ddb5292ac9a9f77e869211ad4c7d244765806cd4",
          "md5": "a48c313c5408be3a35db1d5d8dc1e796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        }
      ],
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 4945,
          "sha512": "9832efa5a84dbb8929305f889f4905b64295b5586be93d5944d16c2fba3a7947dae1d3f79c02ed6bd66d819724cb0804f3fcfc2f9c4929973ac208979a1c58e8",
          "sha256": "6a929a90e52694bb82071a6028891d7509b48094acc06cada1b7a84af9c96964",
          "sha1": "ddb5292ac9a9f77e869211ad4c7d244765806cd4",
          "md5": "a48c313c5408be3a35db1d5d8dc1e796"
        }
      ]
    }
  ]
}
