{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "memory-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 4801,
          "sha512": "1caec445878986e876b24c4ca15b5fc3e378333a7f5317ead79472e1dd1fd7432519e2281eff17e6c4ab4b05b41cde6212f3865b8a8b8cde2f5c669683b9c305",
          "sha256": "48381870e9b6b5206ac48c245a0537d761419f0925404996841fd9d0ae8290cc",
          "sha1": "def96b340f402f90ce99e74eac0baec382b2cd58",
          "md5": "f9e2465dde9a7325c2553f03d9c78cae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        }
      ],
      "files": [
        {
          "name": "memory-management-1.0.0.jar",
          "url": "memory-management-1.0.0.jar",
          "size": 4801,
          "sha512": "1caec445878986e876b24c4ca15b5fc3e378333a7f5317ead79472e1dd1fd7432519e2281eff17e6c4ab4b05b41cde6212f3865b8a8b8cde2f5c669683b9c305",
          "sha256": "48381870e9b6b5206ac48c245a0537d761419f0925404996841fd9d0ae8290cc",
          "sha1": "def96b340f402f90ce99e74eac0baec382b2cd58",
          "md5": "f9e2465dde9a7325c2553f03d9c78cae"
        }
      ]
    }
  ]
}
