package rules_id_lipid_expert_knowledge.negative;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.CommonAdductNegative;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.lipids.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.FoundAdduct;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.params.MobilePhases;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.params.SampleTypes;
import java.util.List;

// Declare the global list
global FoundLipid lipid;
global List mobilePhases;
global SampleTypes sampleType;

rule "Presence [M-H]-"
when
    $adduct: FoundAdduct(adductName == "[M-H]-")
    eval(sampleType == SampleTypes.PLASMA)
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M-H]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end
rule "No presence [M+CH3COO]-"
when
    not FoundAdduct(adductName == "[M+CH3COO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval(sampleType == SampleTypes.PLASMA)
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+CH3COO]-, ");
    List<FoundAdduct> adducts = lipid.getListAdducts();
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Presence [M+CH3COO]-"
when
    $adduct: FoundAdduct(adductName == "[M+CH3COO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval(sampleType == SampleTypes.PLASMA)
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+CH3COO]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Presence [M+HCOO]-"
when
    $adduct: FoundAdduct(adductName == "[M+HCOO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.HCOO)
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+HCOO]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Presence [M+Cl]-"
when
    $adduct: FoundAdduct(adductName == "[M+Cl]-")
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Cl]-, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end




rule "Intensity [M+CH3COO]- > [M-H]-"
when
    $adduct1: FoundAdduct(adductName == "[M+CH3COO]-")
    $adduct2: FoundAdduct(adductName == "[M-H]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval($adduct1.getIntensity() > $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+CH3COO]- > [M-H]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+CH3COO]- > [M+Cl]-"
when
    $adduct1: FoundAdduct(adductName == "[M+CH3COO]-")
    $adduct2: FoundAdduct(adductName == "[M+Cl]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval($adduct1.getIntensity() > $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+CH3COO]- > [M+Cl]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M-H]- > [M+HCOO]-"
when
    $adduct1: FoundAdduct(adductName == "[M-H]-")
    $adduct2: FoundAdduct(adductName == "[M+HCOO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.HCOO)
    eval($adduct1.getIntensity() > $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M-H]- > [M+HCOO]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+Cl]- > [M+HCOO]-"
when
    $adduct1: FoundAdduct(adductName == "[M+Cl]-")
    $adduct2: FoundAdduct(adductName == "[M+HCOO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.HCOO)
    eval($adduct1.getIntensity() > $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Cl]- > [M+HCOO]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end


rule "Intensity [M+CH3COO]- < [M-H]-"
when
    $adduct1: FoundAdduct(adductName == "[M+CH3COO]-")
    $adduct2: FoundAdduct(adductName == "[M-H]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval($adduct1.getIntensity() < $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+CH3COO]- < [M-H]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+CH3COO]- < [M+Cl]-"
when
    $adduct1: FoundAdduct(adductName == "[M+CH3COO]-")
    $adduct2: FoundAdduct(adductName == "[M+Cl]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    eval($adduct1.getIntensity() < $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+CH3COO]- < [M+Cl]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M-H]- < [M+HCOO]-"
when
    $adduct1: FoundAdduct(adductName == "[M-H]-")
    $adduct2: FoundAdduct(adductName == "[M+HCOO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.HCOO)
    eval($adduct1.getIntensity() < $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M-H]- < [M+HCOO]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+Cl]- < [M+HCOO]-"
when
    $adduct1: FoundAdduct(adductName == "[M+Cl]-")
    $adduct2: FoundAdduct(adductName == "[M+HCOO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.HCOO)
    eval($adduct1.getIntensity() < $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then
    
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Cl]- < [M+HCOO]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+CH3COO]- < [M+HCOO]-"
when
    $adduct1: FoundAdduct(adductName == "[M+HCOO]-")
    $adduct2: FoundAdduct(adductName == "[M+CH3COO]-")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.CH3COO)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.HCOO)
    eval($adduct1.getIntensity() > $adduct2.getIntensity())
    eval(sampleType == SampleTypes.PLASMA)
then

    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+HCOO]- > [M+CH3COO]-, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end