package rules_id_lipid_expert_knowledge.negative;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.CommonAdductNegative;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.lipids.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.FoundAdduct;


// Declare the global list
global java.util.List<FoundLipid> detectedLipids;
global FoundLipid lipid;

rule "Presence [M-H]-"
when
    $adduct: FoundAdduct(adductName == "[M-H]-")
then
    
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M-H]-; ");
    //detectedLipids.add(lipid);
end

rule "Presence [M-H+(CH3COONa)]-"
when
    $adduct: FoundAdduct(adductName == "[M-H+(CH3COONa)]-")
then
    
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M-H+(CH3COONa)]-; ");
    //detectedLipids.add(lipid);
end

rule "Presence [M+CH3COO]-"
when
    $adduct: FoundAdduct(adductName == "[M+CH3COO]-")
then
    
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+CH3COO]-; ");
    //detectedLipids.add(lipid);
end

rule "Presence [M+Cl]-"
when
    $adduct: FoundAdduct(adductName == "[M+Cl]-")
then
    
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Cl]-; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+CH3COO]- > [M-H]-"
when
    $adduct1: FoundAdduct(adductName == "[M+CH3COO]-")
    $adduct2: FoundAdduct(adductName == "[M-H]-")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Intensity OK [M+CH3COO]- > [M-H]-; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M-H]- > [M+Cl]-"
when
    $adduct1: FoundAdduct(adductName == "[M-H]-")
    $adduct2: FoundAdduct(adductName == "[M+Cl]-")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Intensity OK [M-H]- > [M+Cl]-; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+Cl]- > [M-H+(CH3COONa)]-"
when
    $adduct1: FoundAdduct(adductName == "[M+Cl]-")
    $adduct2: FoundAdduct(adductName == "[M-H+(CH3COONa)]-")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Intensity OK [M+Cl]- > [M-H+(CH3COONa)]-; ");
    //detectedLipids.add(lipid);
end


rule "Intensity [M+CH3COO]- < [M-H]-"
when
    $adduct1: FoundAdduct(adductName == "[M+CH3COO]-")
    $adduct2: FoundAdduct(adductName == "[M-H]-")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Intensity NOT OK [M+CH3COO]- < [M-H]-; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M-H]- < [M+Cl]-"
when
    $adduct1: FoundAdduct(adductName == "[M-H]-")
    $adduct2: FoundAdduct(adductName == "[M+Cl]-")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Intensity NOT OK [M-H]- < [M+Cl]-; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+Cl]- < [M-H+(CH3COONa)]-"
when
    $adduct1: FoundAdduct(adductName == "[M+Cl]-")
    $adduct2: FoundAdduct(adductName == "[M-H+(CH3COONa)]-")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Cl]- < [M-H+(CH3COONa)]-; ");
    //detectedLipids.add(lipid);
end