{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "mzmine-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 10466,
          "sha512": "05a5a265985e4921476071db660aa500d3685fe4a7181f059f16870635a80402324b7ff677edd5a4d059b194feaa90430257106a8d6a8f0eb63cd1dda9c50e06",
          "sha256": "f6f277ec0e431c55690c4e2a5b4261594a3df1d52959e9fc883c9ee90c9ccdcb",
          "sha1": "3b8465f26e8a9745ed75dcc907cb9b3dd9ebed33",
          "md5": "5d4dc17b34271a34627de3893e8bfd9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        }
      ],
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 10466,
          "sha512": "05a5a265985e4921476071db660aa500d3685fe4a7181f059f16870635a80402324b7ff677edd5a4d059b194feaa90430257106a8d6a8f0eb63cd1dda9c50e06",
          "sha256": "f6f277ec0e431c55690c4e2a5b4261594a3df1d52959e9fc883c9ee90c9ccdcb",
          "sha1": "3b8465f26e8a9745ed75dcc907cb9b3dd9ebed33",
          "md5": "5d4dc17b34271a34627de3893e8bfd9c"
        }
      ]
    }
  ]
}
