{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "mzmine-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 13270,
          "sha512": "c4ecb3d3688a753088c7b55fd261f93af3279b5561f09af583c0a49931f083fc0f5c9c7b6090b210fc2126894fb8d2a8e4abf556fa5e7878ac90cd56163a37d5",
          "sha256": "b9b79f4867febd54de937a90f082edd8dbbe91cbfbbdf8481ed2b21be9f7663e",
          "sha1": "0e8b0aa11084c4b3e1229d34844839ffd3a7d9fd",
          "md5": "a166224d9a0f8477457599a2b6cac06e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.1.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "23.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 13270,
          "sha512": "c4ecb3d3688a753088c7b55fd261f93af3279b5561f09af583c0a49931f083fc0f5c9c7b6090b210fc2126894fb8d2a8e4abf556fa5e7878ac90cd56163a37d5",
          "sha256": "b9b79f4867febd54de937a90f082edd8dbbe91cbfbbdf8481ed2b21be9f7663e",
          "sha1": "0e8b0aa11084c4b3e1229d34844839ffd3a7d9fd",
          "md5": "a166224d9a0f8477457599a2b6cac06e"
        }
      ]
    }
  ]
}
