{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "mzmine-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 10246,
          "sha512": "c411861ebf6e82b38fb57915a99f68f07d8bb6334b4790e826061ceb4b5524b3bf2d96289e3a1f999dba16f445614aa4bc491633b3944c5bfffaeecf314ab8a3",
          "sha256": "4eacf7f1028975f4e4cfd2c8348a892a14626d18862a2a8aed8c263d0a155d00",
          "sha1": "6dc62265dd6fc3c38ac9d06cea07f2535dde758c",
          "md5": "2aa72d356cbb239d9315bfacb59c117a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        }
      ],
      "files": [
        {
          "name": "mzmine-core-1.0.0.jar",
          "url": "mzmine-core-1.0.0.jar",
          "size": 10246,
          "sha512": "c411861ebf6e82b38fb57915a99f68f07d8bb6334b4790e826061ceb4b5524b3bf2d96289e3a1f999dba16f445614aa4bc491633b3944c5bfffaeecf314ab8a3",
          "sha256": "4eacf7f1028975f4e4cfd2c8348a892a14626d18862a2a8aed8c263d0a155d00",
          "sha1": "6dc62265dd6fc3c38ac9d06cea07f2535dde758c",
          "md5": "2aa72d356cbb239d9315bfacb59c117a"
        }
      ]
    }
  ]
}
