{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management-fx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-fx-1.0.0.jar",
          "url": "user-management-fx-1.0.0.jar",
          "size": 55923,
          "sha512": "b5751a1b9f7d4c5b6514d48b8cf0434b0783053a1d9348fb6252452efd1cbc3788d99982bfc417fc3dc34941750fa8e865669dc18d80ca5f1ac066b51b388b35",
          "sha256": "ae35d7d98e6f85c21041e96d9886e692c590ae2865436d332ae8f245185044f3",
          "sha1": "a1fea6e8ef15005276b98a4eaa5d281d4ace62bc",
          "md5": "57296b8329bd2ddc6d499aace9804c39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.2.2"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "javafx-framework"
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "24"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-fx-1.0.0.jar",
          "url": "user-management-fx-1.0.0.jar",
          "size": 55923,
          "sha512": "b5751a1b9f7d4c5b6514d48b8cf0434b0783053a1d9348fb6252452efd1cbc3788d99982bfc417fc3dc34941750fa8e865669dc18d80ca5f1ac066b51b388b35",
          "sha256": "ae35d7d98e6f85c21041e96d9886e692c590ae2865436d332ae8f245185044f3",
          "sha1": "a1fea6e8ef15005276b98a4eaa5d281d4ace62bc",
          "md5": "57296b8329bd2ddc6d499aace9804c39"
        }
      ]
    }
  ]
}
