{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management-fx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-fx-1.0.0.jar",
          "url": "user-management-fx-1.0.0.jar",
          "size": 52909,
          "sha512": "81f2eb0bbac469bd41acedd2bacc59ea5d66e905ed53e8b40415545ae71a916a702052ce8c72b8c1f94286f3c3fd70ac178b3098aaf8fa1b9ffcc0cfbd398c5a",
          "sha256": "e1f6a96ad75a0f7d9d9f7675054d9540dcb0269a70e50e70140adab7fc219f29",
          "sha1": "28cb8ed3a829feb0763042bc3ee93dbea5953717",
          "md5": "68f5387d49e9caa0900878f3a53954e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.2.2"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "javafx-framework"
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "23.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-fx-1.0.0.jar",
          "url": "user-management-fx-1.0.0.jar",
          "size": 52909,
          "sha512": "81f2eb0bbac469bd41acedd2bacc59ea5d66e905ed53e8b40415545ae71a916a702052ce8c72b8c1f94286f3c3fd70ac178b3098aaf8fa1b9ffcc0cfbd398c5a",
          "sha256": "e1f6a96ad75a0f7d9d9f7675054d9540dcb0269a70e50e70140adab7fc219f29",
          "sha1": "28cb8ed3a829feb0763042bc3ee93dbea5953717",
          "md5": "68f5387d49e9caa0900878f3a53954e7"
        }
      ]
    }
  ]
}
