{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "taskcontroller",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "taskcontroller-1.0.0.jar",
          "url": "taskcontroller-1.0.0.jar",
          "size": 19775,
          "sha512": "60920999ecda1589a2e9189bd48848df14bd37c58b5fbbfffc74b3c505b087cab381a124a78c17aff70baa03bcaf3cee5394ffaf1cb595e6d28f7353e33abc01",
          "sha256": "6840160db748c0a9fac5ebb820911497f416ac376fd32a2c6e66ca0de7cae55c",
          "sha1": "527da265a8f7d19d902388f696e6a6be66ef9fe5",
          "md5": "8020c4f055ce2860fa8220b0ffe8edc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-fxml",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "21"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "win"
            }
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.1.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "io.mzio",
          "module": "memory-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "taskcontroller-1.0.0.jar",
          "url": "taskcontroller-1.0.0.jar",
          "size": 19775,
          "sha512": "60920999ecda1589a2e9189bd48848df14bd37c58b5fbbfffc74b3c505b087cab381a124a78c17aff70baa03bcaf3cee5394ffaf1cb595e6d28f7353e33abc01",
          "sha256": "6840160db748c0a9fac5ebb820911497f416ac376fd32a2c6e66ca0de7cae55c",
          "sha1": "527da265a8f7d19d902388f696e6a6be66ef9fe5",
          "md5": "8020c4f055ce2860fa8220b0ffe8edc3"
        }
      ]
    }
  ]
}
