{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "taskcontroller",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "taskcontroller-1.0.0.jar",
          "url": "taskcontroller-1.0.0.jar",
          "size": 35054,
          "sha512": "8dbc5c2d2a55e2c622560b01046c1fb95602c2935dadf7e8934a618e1be36b8cdd8596d1ef0dcc87eecb6a317bf16a84a9790bf72dd0cc853cb61dfc5a5d80ff",
          "sha256": "989aac68bae9b2d7a9fe881a012663d1fd04f093c0f2e2f02c35315d1e219806",
          "sha1": "f5b43e24a22512c55ed3011809e3873f02b36216",
          "md5": "6d6e94713cda6c8d11ee6b4168d6cf07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 26,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.2.2"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "io.mzio",
          "module": "memory-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "24"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "24"
          }
        }
      ],
      "files": [
        {
          "name": "taskcontroller-1.0.0.jar",
          "url": "taskcontroller-1.0.0.jar",
          "size": 35054,
          "sha512": "8dbc5c2d2a55e2c622560b01046c1fb95602c2935dadf7e8934a618e1be36b8cdd8596d1ef0dcc87eecb6a317bf16a84a9790bf72dd0cc853cb61dfc5a5d80ff",
          "sha256": "989aac68bae9b2d7a9fe881a012663d1fd04f093c0f2e2f02c35315d1e219806",
          "sha1": "f5b43e24a22512c55ed3011809e3873f02b36216",
          "md5": "6d6e94713cda6c8d11ee6b4168d6cf07"
        }
      ]
    }
  ]
}
