{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "taskcontroller",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "taskcontroller-1.0.0.jar",
          "url": "taskcontroller-1.0.0.jar",
          "size": 20021,
          "sha512": "029438209d6be1528a8613c714b8d1653a73b2ef2412b0ba8128c2fbfc8373efb113274541876717e142efdf9604fce067e0f694da33bcd25b20af98757f5f80",
          "sha256": "9525e51b991b9d61ae1211366db6456e010ab7401cfd07140ab186aeb33e0c33",
          "sha1": "94d5418f548c675e7acedf64aa9f29b292e793bd",
          "md5": "2d286cee376bf537818052751e36a2fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.1.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "io.mzio",
          "module": "memory-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "21"
          }
        }
      ],
      "files": [
        {
          "name": "taskcontroller-1.0.0.jar",
          "url": "taskcontroller-1.0.0.jar",
          "size": 20021,
          "sha512": "029438209d6be1528a8613c714b8d1653a73b2ef2412b0ba8128c2fbfc8373efb113274541876717e142efdf9604fce067e0f694da33bcd25b20af98757f5f80",
          "sha256": "9525e51b991b9d61ae1211366db6456e010ab7401cfd07140ab186aeb33e0c33",
          "sha1": "94d5418f548c675e7acedf64aa9f29b292e793bd",
          "md5": "2d286cee376bf537818052751e36a2fd"
        }
      ]
    }
  ]
}
