package io.github.mzmine.modules.dataprocessing.id_lipididentification.lipididentificationtools;

public enum LipidFragmentationRuleType {
  
	HEADGROUP_FRAGMENT, //
	HEADGROUP_FRAGMENT_NL, //
	ACYLCHAIN_FRAGMENT, //
	ACYLCHAIN_FRAGMENT_NL, //
	ACYLCHAIN_PLUS_FORMULA_FRAGMENT, //
	ACYLCHAIN_PLUS_FORMULA_FRAGMENT_NL, //
	ACYLCHAIN_MINUS_FORMULA_FRAGMENT, //
	ACYLCHAIN_MINUS_FORMULA_FRAGMENT_NL, //
	TWO_ACYLCHAINS_PLUS_FORMULA_FRAGMENT, //
	ALKYLCHAIN_FRAGMENT, //
	ALKYLCHAIN_FRAGMENT_NL, //
	ALKYLCHAIN_PLUS_FORMULA_FRAGMENT, //
	ALKYLCHAIN_PLUS_FORMULA_FRAGMENT_NL, //
	ALKYLCHAIN_MINUS_FORMULA_FRAGMENT, //
	ALKYLCHAIN_MINUS_FORMULA_FRAGMENT_NL,//
  
}
