package io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.rules;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.CommonAdductPositive;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.FoundAdduct;


// Declare the global list
global java.util.List<FoundLipid> detectedLipids;
global FoundLipid lipid;

rule "Presence [M+H]+"
when
    $adduct: FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+; ");
    //detectedLipids.add(lipid);
end
