package rules_id_lipid_expert_knowledge.positive;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.CommonAdductPositive;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.lipids.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.FoundAdduct;

// Declare the global list
global java.util.List<FoundLipid> detectedLipids;
global FoundLipid lipid;


rule "Presence [M+H]+"
when
    $adduct: FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+; ");
end
rule "No presence [M+C2H7N2]+"
when
    not FoundAdduct(adductName == "[M+C2H7N2]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+C2H7N2]+; ");
end

rule "Presence [M+Na]+"
when
    $adduct: FoundAdduct(adductName == "[M+Na]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+; ");
end

rule "Presence [M+K]+"
when
    $adduct: FoundAdduct(adductName == "[M+K]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+; ");
end

rule "Presence [M+C2H7N2]+"
when
    $adduct: FoundAdduct(adductName == "[M+C2H7N2]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+C2H7N2]+; ");
end

rule "Presence [M+NH4]+"
when
    $adduct: FoundAdduct(adductName == "[M+NH4]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+NH4]+; ");
end

rule "Presence [M+H-H2O]+"
when
    $adduct: FoundAdduct(adductName == "[M+H-H2O]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H-H2O]+; ");
end



rule "Intensity [M+NH4]+ > [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+NH4]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+NH4]+ > [M+Na]+; ");
end

rule "Intensity [M+Na]+ > [M+H]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+H]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+H]+; ");
end

rule "Intensity [M+Na]+ > [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+K]+; ");
end

rule "Intensity [M+Na]+ > [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+C2H7N2]+; ");
end

rule "Intensity [M+NH4]+ < [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+NH4]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+NH4]+ < [M+Na]+; ");
end

rule "Intensity [M+Na]+ < [M+H]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+H]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+H]+; ");
end

rule "Intensity [M+Na]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+K]+; ");
end

rule "Intensity [M+Na]+ < [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+C2H7N2]+; ");
end

rule "Intensity [M+H]+ > [M+NH4]+"
when
    $adduct2: FoundAdduct(adductName == "[M+H]+")
    $adduct1: FoundAdduct(adductName == "[M+NH4]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ > [M+NH4]+; ");
end

rule "Intensity [M+K]+ > [M+NH4]+"
when
    $adduct2: FoundAdduct(adductName == "[M+K]+")
    $adduct1: FoundAdduct(adductName == "[M+NH4]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+K]+ > [M+NH4]+; ");
end

rule "Intensity [M+C2H7N2]+ > [M+NH4]+"
when
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")
    $adduct1: FoundAdduct(adductName == "[M+NH4]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+C2H7N2]+ > [M+NH4]+; ");
end