package rules_id_lipid_expert_knowledge.positive;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.CommonAdductPositive;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.lipids.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.FoundAdduct;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.params.MobilePhases;
import java.util.List;

// Declare the global list
global FoundLipid lipid;
global List mobilePhases;
global String sampleType;


rule "Presence [M+H]+"
when
    $adduct: FoundAdduct(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end
rule "No presence [M+H]+"
when
    not FoundAdduct(adductName == "[M+H]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+H]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Presence [M+Na]+"
when
    $adduct: FoundAdduct(adductName == "[M+Na]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Presence [M+K]+"
when
    $adduct: FoundAdduct(adductName == "[M+K]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end

rule "Presence [M+H-H2O]+"
when
    $adduct: FoundAdduct(adductName == "[M+H-H2O]+")
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H-H2O]+, ");
    lipid.setAppliedPresence(lipid.getAppliedPresence() + 1);
end




rule "Intensity [M+H]+ > [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+Na]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+Na]+ > [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+K]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+H]+ < [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+Na]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+Na]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+K]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end

rule "Intensity [M+H]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+K]+")
    $adduct2: FoundAdduct(adductName == "[M+H]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
     eval(sampleType.equalsIgnoreCase("PLASMA"))
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+K]+ > [M+H]+, ");
    lipid.setAppliedIntensity(lipid.getAppliedIntensity() + 1);
end
