package rules_id_lipid_expert_knowledge.positive;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.CommonAdductPositive;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.lipids.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.FoundAdduct;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.params.MobilePhases;
import java.util.List;

// Declare the global list
global FoundLipid lipid;
global List mobilePhases;


rule "Presence [M+H]+"
when
    $adduct: FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+, ");
end
rule "No presence [M+H]+"
when
    not FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+H]+, ");
end

rule "Presence [M+Na]+"
when
    $adduct: FoundAdduct(adductName == "[M+Na]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+, ");
end

rule "Presence [M+K]+"
when
    $adduct: FoundAdduct(adductName == "[M+K]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+, ");
end

rule "Presence [M+C2H7N2]+"
when
    $adduct: FoundAdduct(adductName == "[M+C2H7N2]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+C2H7N2]+, ");
end

rule "Presence [M+H-H2O]+"
when
    $adduct: FoundAdduct(adductName == "[M+H-H2O]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H-H2O]+, ");
end




rule "Intensity [M+H]+ > [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+Na]+, ");
end

rule "Intensity [M+H]+ > [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+C2H7N2]+, ");
end

rule "Intensity [M+Na]+ > [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+K]+, ");
end

rule "Intensity [M+C2H7N2]+ > [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+C2H7N2]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+C2H7N2]+ > [M+K]+, ");
end

rule "Intensity [M+H]+ < [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+Na]+, ");
end

rule "Intensity [M+H]+ < [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+C2H7N2]+, ");
end

rule "Intensity [M+Na]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+K]+, ");
end

rule "Intensity [M+C2H7N2]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+C2H7N2]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")
    $phase1 : MobilePhases() from mobilePhases
    eval($phase1 == MobilePhases.NH4)
    $phase2 : MobilePhases() from mobilePhases
    eval($phase2 == MobilePhases.CH3CN)
    $phase3 : MobilePhases() from mobilePhases
    eval($phase3 == MobilePhases.CH3OH)

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+C2H7N2]+ < [M+K]+, ");
end

rule "Intensity [M+H]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+K]+")
    $adduct2: FoundAdduct(adductName == "[M+H]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+K]+ > [M+H]+, ");
end