package rules_id_lipid_expert_knowledge.positive;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.CommonAdductPositive;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.lipids.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.adducts.FoundAdduct;

// Declare the global list
global java.util.List<FoundLipid> detectedLipids;
global FoundLipid lipid;

rule "Presence [M+H]+"
when
    $adduct: FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+; ");
end
rule "No presence [M+H]+"
when
    not FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+H]+; ");
end

rule "Presence [M+Na]+"
when
    $adduct: FoundAdduct(adductName == "[M+Na]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+; ");
end
rule "No presence [M+Na]+"
when
    not FoundAdduct(adductName == "[M+Na]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+Na]+; ");
end

rule "Presence [M+K]+"
when
    $adduct: FoundAdduct(adductName == "[M+K]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+; ");
end
rule "No presence [M+K]+"
when
    not FoundAdduct(adductName == "[M+K]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+K]+; ");
end

rule "Presence [M+C2H7N2]+"
when
    $adduct: FoundAdduct(adductName == "[M+C2H7N2]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+C2H7N2]+; ");
end
rule "No presence [M+C2H7N2]+"
when
    not FoundAdduct(adductName == "[M+C2H7N2]+")
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Missing [M+C2H7N2]+; ");
end

rule "Intensity [M+H]+ > [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+Na]+; ");
end


rule "Intensity [M+Na]+ > [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+K]+; ");
end

rule "Intensity [M+Na]+ > [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(2);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+C2H7N2]+; ");
end

rule "Intensity [M+H]+ < [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+Na]+; ");
end

rule "Intensity [M+Na]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+K]+; ");
end

rule "Intensity [M+Na]+ < [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-2);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+C2H7N2]+; ");
end