package io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.rules;

import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.CommonAdductPositive;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.FoundLipid;
import io.github.mzmine.modules.dataprocessing.id_lipidid_expertknowledge.utils.FoundAdduct;

// Declare the global list
global java.util.List<FoundLipid> detectedLipids;
global FoundLipid lipid;

rule "Presence [M+H]+"
when
    $adduct: FoundAdduct(adductName == "[M+H]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+H]+; ");
    //detectedLipids.add(lipid);
end

rule "Presence [M+Na]+"
when
    $adduct: FoundAdduct(adductName == "[M+Na]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+Na]+; ");
    //detectedLipids.add(lipid);
end

rule "Presence [M+K]+"
when
    $adduct: FoundAdduct(adductName == "[M+K]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+K]+; ");
    //detectedLipids.add(lipid);
end

rule "Presence [M+C2H7N2]+"
when
    $adduct: FoundAdduct(adductName == "[M+C2H7N2]+")
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Contains [M+C2H7N2]+; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+H]+ > [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Intensity OK [M+H]+ > [M+Na]+; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+Na]+ > [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+K]+; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+Na]+ > [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")

    eval($adduct1.getIntensity() > $adduct2.getIntensity())
then
    lipid.setScore(1);
    lipid.setDescrCorrect("Intensity OK [M+Na]+ > [M+C2H7N2]+; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+H]+ < [M+Na]+"
when
    $adduct1: FoundAdduct(adductName == "[M+H]+")
    $adduct2: FoundAdduct(adductName == "[M+Na]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Intensity NOT OK [M+H]+ < [M+Na]+; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+Na]+ < [M+K]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+K]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+K]+; ");
    //detectedLipids.add(lipid);
end

rule "Intensity [M+Na]+ < [M+C2H7N2]+"
when
    $adduct1: FoundAdduct(adductName == "[M+Na]+")
    $adduct2: FoundAdduct(adductName == "[M+C2H7N2]+")

    eval($adduct1.getIntensity() < $adduct2.getIntensity())
then
    lipid.setScore(-1);
    lipid.setDescrIncorrect("Intensity NOT OK [M+Na]+ < [M+C2H7N2]+; ");
    //detectedLipids.add(lipid);
end