name: Check dependency licenses

on:
  pull_request:
    branches: [ "master" ]

jobs:
  gradle_build:
    name: test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup java
        uses: actions/setup-java@v5
        with:
#          distribution: 'temurin' # had issues for jdk25.0.0
          distribution: 'zulu'
          java-version: '25.0.0'
#          cache: 'gradle'  # now done with gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Execute dependency license check
        run: ./gradlew mzmine-community:checkLicense --stacktrace

      - name: Upload license report
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: license_report
          path: mzmine-community/licensereport/*.json
          retention-days: 7  # store for 7 days
